### PR TITLE
COMMERCE-1777 Add to wishlist is enabled only when account is selected

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by gianmarcobrunialti** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by ethanbustad** [comment]
ci:test
Tests may pass now that https://github.com/liferay/com-liferay-commerce/pull/1436 is merged in.

**Comment by gianmarcobrunialti** [comment]
@marco-leo Re-committed the translations.

**Comment by marco-leo** [comment]
Please see COMMERCE-2082. This pull add a no valid flow.

**Comment by gianmarcobrunialti** [comment]
@marco-leo I see the flow has consolidated somehow. 😛

**Pull request closed without merging**
