### PR TITLE
COMMERCE-998 B2C-B2B Site Admin should see both types of accounts

### PR DESCRIPTION
**Pull request by alecsloan**
Let me know if you have any questions.

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by yichenroy** [comment]
There were issues with the hardware that IT is currently investigating, please try retesting in a little while.

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by marco-leo** [comment]
@alecsloan This is not the right solution. Let's talk over it

**Pull request merged**
