### PR TITLE
LRQA-46625 | 7.1.x-next

### PR DESCRIPTION
**Pull request by iovaneale**
https://issues.liferay.com/browse/LRQA-46625

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
@marco-leo here is the new rebased pull

**Comment by marco-leo** [comment]
@iovaneale Test failing

**Comment by iovaneale** [comment]
ci:retest

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
@ethanbustad, SF doesn't catch any error locally. I have also rebased my branch but the errors is still thrown, do you have any idea of why?

/cc @marco-leo

**Comment by ethanbustad** [comment]
ci:test
My best guess is that com-liferay-commerce-private:7.1.x-next wasn't up-to-date with the public one, so even though you rebased it still wasn't using the latest code? We'll see. Everything looks right to me on 7.1.x-next now, so if it fails again we'll probably need to ping CI Infra about it.

**Comment by iovaneale** [comment]
Sent to #627

**Pull request closed without merging**
