### PR TITLE
COMMERCE-1951 changes according to PRs

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
Hi @ethanbustad , I don't understand this failure, I've jus run locally the baseLine command but no changes were made on the semantic versioning

**Comment by marco-leo** [comment]
just retesting, looks a failur in CI  ci:test

**Comment by ethanbustad** [comment]
ci:test
Yep, just a failure in CI. Every once-in-a-while we get this `Premature end of Content-Length delimited message body` error -- still not sure why. But it's only a problem in CI.

**Review by ethanbustad — APPROVED** [review]

**Pull request merged**
