### PR TITLE
Make Minium login splash and logo customizable

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
Forgot to update private branch :'(

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
Won't merge this pull request, please it using theme settings, and avoiding ovveride

**Pull request closed without merging**
