### PR TITLE
COMMERCE-828

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
[Commerce API Scrum board](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=3928)
----
Ticket: https://issues.liferay.com/browse/COMMERCE-828

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:stop

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:test

**Review by marco-leo — APPROVED** [review]

**Comment by ethanbustad** [comment]
ci:test
Should be fixed by https://github.com/liferay/com-liferay-commerce/pull/430.

**Pull request merged**
