### PR TITLE
COMMERCE-2481 Added new theme setting

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by ethanbustad** [comment]
@Commando18 just the indentation issue to fix, as flagged by SF

**Comment by marco-leo** [comment]
@alecsloan please take a look to this PR just for future implementations //cc @FabioDiegoMastrorilli  @gianmarcobrunialti @gcmznt

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/1708

**Pull request closed without merging**
