### PR TITLE
COMMERCE-874 Fix commerce-cart-taglib deploy issue (7.1.x)

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-874

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@marco-leo merging to fix CI.

**Comment by NaderJafari** [comment]
> 
> 
> https://issues.liferay.com/browse/COMMERCE-874

Hi
Why can't i see this issue in jira?

**Comment by ethanbustad** [comment]
@marco-leo merging this in to fix CI issues.

**Comment by ethanbustad** [comment]
Sorry, @naderjafari, the COMMERCE project is currently a private project in JIRA. We're working on making it public, as that would obviously be preferable! Either way you'd need a valid issues.liferay.com account, just fyi.

**Pull request merged**
