### PR TITLE
COMMERCE-1176 Use the account's groupId instead of sites to delete workflow

### PR DESCRIPTION
**Pull request by alecsloan**
@marco-leo hopefully this is the fix you're looking for

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
@alecsloan requires a SF fix

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Pull request merged**
