### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
@ethanbustad @iovaneale this pull is fixing the bug that fuctional test are complaining

**Review by ethanbustad — APPROVED** [review]

**Comment by alecsloan** [comment]
@marco-leo instead of COMMERCE-1623, shouldn't it be this ticket? https://issues.liferay.com/browse/COMMERCE-1687

**Comment by marco-leo** [comment]
ci:test

**Pull request merged**
