### PR TITLE
COMMERCE-1953 Implement npmResolver in product-definitions-web

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by marco-leo** [comment]
@alecsloan About this pull, from FP13 we should have a variable npmResolver directly injected in the jsp i think, should simplify a lot

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:stop

**Comment by alecsloan** [comment]
ci:test

**Pull request merged**
