### PR TITLE
COMMERCE-1988 Minium template proper ID's for 7.2 compat

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
Working fix for 7.2 compatibility *before* fully upgrading the Minium theme according to [this procedure](https://help.liferay.com/hc/en-us/articles/360029005612-Upgrading-7-1-Themes-to-7-2)

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test

**Review by ethanbustad — COMMENTED** [review]
Just remove the trailing newline please ;)

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
@gianmarcobrunialti is a valid fix? Can you make pass the SFs and make sure we have the same fix in speedwell?

**Comment by gianmarcobrunialti** [comment]
@marco-leo I'm not sure this is a valid fix anymore. Based on what @jbalsas said, this should *not* be the fix we need, the problem of 7.2 compat for Minium and Speedwell is solely related to the update of configuration files as described here: 
* https://issues.liferay.com/browse/COMMERCE-2017
* https://issues.liferay.com/browse/COMMERCE-1992

The PR for COMMERCE-1992 is here: https://github.com/liferay/com-liferay-commerce/pull/1472 and this completes COMMERCE-2017 as well.

**Pull request closed without merging**
