### PR TITLE
COMMERCE-2369 Shipment Refactor (from Alec)

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-2369

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
@alecsloan This looks like a real fail

**Comment by ethanbustad** [comment]
Forwarded to https://github.com/liferay/com-liferay-commerce/pull/1804.

**Pull request closed without merging**
