### PR TITLE
COMMERCE-1989 Removed unnecessary roles from initializers

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by jpince** [comment]
ci:test

**Comment by kyle-miho** [comment]
@Commando18  can you try to upgrade the gradle.properties
in modules/dxp/apps/commerce to have project.path.prefix of dxp:apps:commerce instead of private:apps:commerce. This causes one of the failures and could possibly fix the others. This was a change in the file structure when 7.1.x-private and 7.1.x merged the dxp apps together

**Comment by ethanbustad** [comment]
@kyle-miho the problem is we can't update that file here.... and we might not be able to update that file anywhere. Needs some further investigation.

**Pull request merged**
