### PR TITLE
COMMERCE-1340

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
@FabioDiegoMastrorilli @ethanbustad  please see my changes, Fabio pleas eupdate css class names and take out minium prefix, and let's fix the breccia detail gallery to works too with many options

**Comment by ethanbustad** [comment]
Should be fixed by https://github.com/liferay/com-liferay-commerce/pull/861.

**Comment by ethanbustad** [comment]
ci:test

**Pull request merged**
