### PR TITLE
Commerce 2479

### PR DESCRIPTION
**Pull request by riccardo-ferrari**

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test

**Comment by riccardo-ferrari** [comment]
ci:test

**Comment by riccardo-ferrari** [comment]
ci:stop

**Comment by riccardo-ferrari** [comment]
ci:test

**Comment by riccardo-ferrari** [comment]
@ethanbustad , just a little change here

**Review by ethanbustad — APPROVED** [review]

**Pull request merged**
