### PR TITLE
COMMERCE-1392 Lang key and default asset renderer

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-1392

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
Should be fixed by https://github.com/liferay/com-liferay-commerce/pull/861.

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
merged in https://github.com/liferay/com-liferay-commerce/pull/872

**Pull request closed without merging**
