### PR TITLE
COMMERCE-2021 Speedwell init fixed after SF and rebase

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
This lacks some permissions check that are getting reviewed by @alecsloan (as far as I know) on the category navigation page. Moreover, the portletPreferences in the layouts.json are grabbed but not used (category navigation again).

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test

**Review by ethanbustad — COMMENTED** [review]
Just the trailing newlines again :). Running `gw formatSource` should fix it I think....

**Comment by marco-leo** [comment]
@ethanbustad can you rebase this and send it with the SF just in this case? so we can run our long ci during the night. Thanks

**Comment by ethanbustad** [comment]
Sent along to https://github.com/liferay/com-liferay-commerce/pull/1446.

**Pull request closed without merging**
