### PR TITLE
COMMERCE-2270 Document for the Nested Fields breaking change.

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
@marco-leo this is just a document for the nested api breaking change

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by ethanbustad** [comment]
@marco-leo @andrea-ale-sbarra this requires some wordsmithing changes. I'll send a follow-up PR with my corrections.

**Comment by ethanbustad** [comment]
Sent to https://github.com/liferay/com-liferay-commerce/pull/1656.

**Pull request closed without merging**
