### PR TITLE
COMMERCE-2482 Fixed minium topbar

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by ethanbustad** [comment]
ci:test
hopefully the semver issues are fixed....

**Comment by ethanbustad** [comment]
ci:test
trying again. hopefully the bundle in use just hadn't been updated yet

**Comment by ethanbustad** [comment]
broken by gradle issues we've been seeing locally. will fix separately

**Comment by ethanbustad** [comment]
ci:test
validation should be working at least now

**Pull request merged**
