### PR TITLE
COMMERCE-738 Make local SF better

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-738

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@yichenroy any idea why this is failing? It starts, but then it fails and removes the original comment. E.g. https://test-1-6.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/41/jenkins-report.html

**Comment by yichenroy** [comment]
This was the failure:
`
     [echo] com.liferay.commerce.product.internal.util.SKUCombinationsIteratorTest > testSKUCombinationsIterator STANDARD_ERROR

     [echo]     SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

     [echo]     SLF4J: Defaulting to no-operation (NOP) logger implementation

     [echo]     SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

     [echo]     Nov 29, 2018 6:40:17 PM com.liferay.portal.kernel.log.Jdk14LogImpl info

     [echo]     INFO: Properties for service loaded from [file:/opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/commerce-product-service/classes/service.properties]`

As for the comment being removed, there may be a problem in the CI script when failures occur, we'll investigate and fix it as soon as possible.

**Comment by yichenroy** [comment]
ci:test
Retesting for comment to be posted properly.

Edit:
We discovered the problem, will be working on the fix for message to be posted properly.

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
last failure was a network timeout

**Comment by ethanbustad** [comment]
ci:test
seriously? comment disappeared again

**Comment by ethanbustad** [comment]
looks like a failure in portal upstream. will wait and try again later.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@hhuijser looks like source formatter isn't picking up our properties right. Can you take a look?

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
@ethanbustad Can you send this to 7.1.x-next ?

**Comment by ethanbustad** [comment]
Sent to 7.1.x-next at https://github.com/liferay/com-liferay-commerce/pull/358.

**Pull request closed without merging**
