### PR TITLE
Clay Table + Data PRovider

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test:a5a92eed847bb441bacf0d22513968422f7b0b25 (7.1.x-next in the public repo is ahead of 7.1.x-next in the private repo)

**Comment by ethanbustad** [comment]
Thanks, @pyoo47. Just updated private repo to see if that would fix it :)

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
Resent to https://github.com/liferay/com-liferay-commerce/pull/306.

**Pull request closed without merging**
