### PR TITLE
COMMERCE-752 Drop Apio Headless API dependencies

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/COMMERCE-752

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test
/cc @marco-leo

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by ZoltanTakacs** [comment]
ci:retest ....

**Comment by marco-leo** [comment]
@Commando18 looks like those errors are related to ur changes. Please take a look

**Comment by ZoltanTakacs** [comment]
@marco-leo the DI related ones are passed see: https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/76/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.commerce.data.integration.apio.resource.test/

`CommerceSubscriptionEntryTest` should be addressed in https://github.com/liferay/com-liferay-commerce/pull/289

I think we can merge this if you don't have any other concerns.

**Pull request merged**
