### PR TITLE
COMMERCE-686 Remove static version

### PR DESCRIPTION
**Pull request by gcmznt**

### CODE REVIEW

**Comment by ethanbustad** [comment]
@marco-leo can we retire COMMERCE-686 and make a new ticket for changes going forward?

**Comment by marco-leo** [comment]
@ethanbustad we do that with new functionalities, for changes to existing or CSS changes, we just use it.  I don't see a real value right now in using many tickets. We still not have backport problems for themes.  Just easier right now. When we will have this kind of prblem to manage we will add more complexity in the project managment for the Front End part of commerce

**Comment by ethanbustad** [comment]
@marco-leo hmmmm... ok. Your call, but I disagree. Every time we commit under COMMERCE-686 (or any other reused ticket) we're missing an opportunity to document why we're doing it. Why are we removing this static version? Don't know -- not documented anywhere. Creating new tickets, even just simple ones, gives us something to go back to in the future when we need to remember why something happened, but it's too long ago for us to remember. I think that's valuable.

**Comment by marco-leo** [comment]
@ethanbustad I see your point and totally agree. In this historic moment of the project, this is not a big problem, we still are doing huge refactoring and changes without worrying about versioning changes and so on, we do need to move fast now. We still don't have to deal with these problems, it will uppen in the near future, no yeat.

**Comment by ethanbustad** [comment]
@marco-leo alright, sounds good.

(PS it will *happen* in the near future, *not* *yet*. :) )

**Comment by marco-leo** [comment]
this pull was duplicated

**Pull request closed without merging**
