### PR TITLE
COMMERCE-441 Fixed portlet preferences per layout

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by iovaneale** [comment]
@ethanbustad, build doesn't start at all, it seems there are problems with subrepo general acceptance again.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@iovaneale @Commando18 we had the same problem in [this](https://github.com/liferay/com-liferay-commerce/pull/122) PR. Apparently it's a known issue that comes up randomly sometimes.

**Comment by ethanbustad** [comment]
ci:test Failure should be fixed by https://github.com/liferay/com-liferay-commerce/pull/137.

**Comment by ethanbustad** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Pull request merged**
