### PR TITLE
COMMERCE-1073-1066-1067 | 7.1.x-next

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
[Commerce API Scrum board](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=3928)
----
Ticket: 
- https://issues.liferay.com/browse/COMMERCE-1067
- https://issues.liferay.com/browse/COMMERCE-1073
- https://issues.liferay.com/browse/COMMERCE-1066

/cc @ivicac

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:test
Rebased to latest `7.1.x-next`

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:close
Closing this one as per our discussion will be resent with updates.

**Pull request closed without merging**
