### PR TITLE
COMMERCE-573 Fixed account menu items

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:retest

**Comment by ethanbustad** [comment]
Error in upstream liferay-portal-ee: https://testray.liferay.com/home/-/testray/case_results/419992135. Ignore.

**Comment by ethanbustad** [comment]
@jpince I think these errors should be fixed by your commit earlier today (https://github.com/liferay/liferay-portal/commit/de2111c57f98d4438934c665a0e3fb291788e83c), except from what I can see the fix hasn't been incorporated into 7.1.x-private (https://github.com/liferay/liferay-portal-ee/commits/7.1.x-private/git-commit-portal). Any way we can get that updated?

**Comment by ethanbustad** [comment]
ci:retest

**Comment by ethanbustad** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Pull request merged**
