### PR TITLE
COMMERCE-0 Add .vscode folder to gitignore

### PR DESCRIPTION
**Pull request by gcmznt**

### CODE REVIEW

**Comment by ethanbustad** [comment]
Hey @gcmznt, this change breaks validation tests so I intentionally reverted this change https://github.com/liferay/com-liferay-commerce/commit/a1870ef29733339f9bbe8b2c3ca784d409011416.

If this is important for you guys, I can talk to the team here to try to get this added to the allowed list of entries in `.gitignore`.

**Comment by marco-leo** [comment]
@ethanbustad @gcmznt let's ask to add that to portal please, is like the .idea folder

**Comment by gcmznt** [comment]
Hi @ethanbustad , as @marco-leo said is a configuration folder for visual studio code editor, so if we want to avoid conflicts of editor settings files it must be ignored

**Comment by ethanbustad** [comment]
Hey @gcmznt , can you guys just configure your editor to save the settings files somewhere else? Other editors like Sublime Text and Atom can do this, and this is how devs in LA are managing. If this is impossible we can explore getting it added to `.gitignore`, but it would require a company-wide configuration change.

**Comment by gcmznt** [comment]
VSCode has 2 levels of settings, one for the user that is in a shared folder, and one for the workspace (the folder of the project). I use the workspace settings because the editor does not work well with our source formatter and it brakes every save the code layout. It also uses the local settings for some java configurations that cannot be shared between different projects.

I have added this folder to the .gitignore file because there is also the .idea folder that has the same function for another editor, so I have put it there for consistency.

But if this is a problem I will look for other solutions. Thank you

**Comment by marco-leo** [comment]
@gcmznt I asked our QA eng to fix the problem. Thanks for reporting it

**Comment by ethanbustad** [comment]
Hmmm alright -- I asked BChan about it earlier today, and he didn't like the idea. We do have eclipse (.project) and IntelliJ (.idea) directories, but we don't have one for _every_ IDE and text editor, and it sounds like BChan doesn't think we should. If there's a particular reason why VSCode stands out as a particular situation where this especially makes sense, we can probably make the case.

**Comment by marco-leo** [comment]
Ok. No worry Ethan I will take care about this. Thanks

**Pull request closed without merging**
