### PR TITLE
COMMERCE-1632 marco ethan igor

### PR DESCRIPTION
**Pull request by igorbeslic**
Liferay please review. Thank yoU!

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test

**Comment by igorbeslic** [comment]
@ethanbustad and @marco-leo this PR is fine now. Error is CI infrastructure I guess. It is not problem with commerce code.

**Comment by marco-leo** [comment]
ci:test

**Comment by alecsloan** [comment]
@marco-leo Looks like this is our failure (fails for pricing.impl and site.setting.impl):
```[junit] Unable to start bundle com.liferay.headless.commerce.admin.pricing.impl
    [junit] org.osgi.framework.BundleException: Could not resolve module: com.liferay.headless.commerce.admin.pricing.impl [655]
    [junit]   Unresolved requirement: Import-Package: com.liferay.commerce.product.service; version="[6.0.0,7.0.0)"

**Comment by alecsloan** [comment]
ci:retest

**Comment by marco-leo** [comment]
merged in https://github.com/liferay/com-liferay-commerce/pull/1214

**Pull request closed without merging**
