### PR TITLE
LPS-99660 Test

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
Forgot to update private branch :'(

**Comment by petershin** [comment]
@ethanbustad - This pull was just for testing and can be closed.

The fix has been pushed to `liferay-portal` master.

**Comment by ethanbustad** [comment]
Oh ok, perfect -- thanks!

**Pull request closed without merging**
