### PR TITLE
COMMERCE-697 | COMMERCE-622

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:stop

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
Hey @ethanbustad 
I fixed the compileJSP error, but I need help to understand why integration tests are failing. Can you please take a look into it?

**Comment by ethanbustad** [comment]
@Commando18 ok, will do!

**Comment by ethanbustad** [comment]
Hey @Commando18, the problem with the integration tests is that:
* An `Exception` needs to be `Serializable`
* `Serializable` has no particular methods that _have_ to be implemented, but all its fields have to be `Serializable`, or if they aren't, it has to implement 3 methods that tell the JVM how to serialize an instance of the class (see https://docs.oracle.com/javase/8/docs/api/java/io/Serializable.html).
* `CommerceOrderValidatorException` is an `Exception`, so it needs to be `Serializable`, but it has a field of type `List<CommerceOrderValidatorResult>` --
* This `List` is implemented as an `ArrayList` in `_commerceOrderValidatorRegistry.validate` -- `ArrayList`s are `Serializable` if their contents are `Serializable` --
* `CommerceOrderValidatorResult` implements `Serializable`, so it should be good, but are its fields?
* `String _argument` is, `long _commerceOrderItemId` is, `String _messageKey` is, `ResourceBundle _resourceBundle` might be we don't know (depends on the implementation), `boolean _valid` is.
* Turns out the `ResourceBundle` is an `AggregateResourceBundle`, **which is not `Serializable`**. This was recently introduced in COMMERCE-711.

Since `AggregateResourceBundle` is a portal class, we can't edit it to make it `Serializable`, but we _can_ add the 3 methods to `CommerceOrderValidatorResult` to make that class actually `Serializable`. We would just need a way to find out exactly what's in the `AggregateResourceBundle` so that we can write it to a String in such a way that provides all the information necessary to put it back together afterwards....

**Comment by alessiorendina** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test
Re-initiating test, previous test did not start due to a CI problem.

**Comment by ethanbustad** [comment]
Resent to https://github.com/liferay/com-liferay-commerce/pull/305.

**Pull request closed without merging**
