### PR TITLE
COMMERCE-686

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by marco-leo** [comment]
@Commando18 can u fix it?

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test:sf

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
merged in https://github.com/liferay/com-liferay-commerce/pull/532

**Pull request closed without merging**
