### PR TITLE
COMMERCE-712 BChan SF

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-712

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test:sf

**Comment by ethanbustad** [comment]
ci:test:sf

**Comment by ethanbustad** [comment]
@yichenroy is the sf task not available in subrepos or something? It seems to break jenkins when I try it....

**Comment by yichenroy** [comment]
@ethanbustad 
Unfortunately ci:test:sf is currently hard-wired to only work for liferay-portal(-ee) pullrequests, it doesn't work on any other repo

**Comment by ethanbustad** [comment]
kk, good to know. Thanks, @yichenroy!

**Comment by ethanbustad** [comment]
ci:test

**Pull request merged**
