### PR TITLE
Data integration management module

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
Continue the work that Guy left at https://github.com/liferay/com-liferay-commerce/pull/219

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by ZoltanTakacs** [comment]
Hi @petershin can you please help me regarding the SF issues here? 
For example we have a `1: Infinite loop in SourceFormatter:` but I have no idea what's causing this..
the other issues are not coming on local when I trigger `gw formatSoruce` is there any other command that I should use to reproduce them locally?

**Comment by petershin** [comment]
Hi @ZoltanTakacs, Hugo will be able to help with the SF issues.

@hhuijser - can you take a look at the SF issues in this pull?

**Comment by ethanbustad** [comment]
Hey @ZoltanTakacs ,

No idea on the infinite loop -- we'll definitely need Hugo's help on that one.

As for reproducing these errors locally, I keep bugging people around here to make this possible, but at the moment I'm pretty sure it's not :(. The best you could do is copy (or symlink?) your commerce repo into portal and run `gw checkSourceFormatting` from there. Oftentimes the difference is that [portal has a bunch of checks enabled](https://github.com/liferay/liferay-portal/blob/7.1.x/source-formatter.properties) that [we don't have in our repo](https://github.com/liferay/com-liferay-commerce/blob/7.1.x/source-formatter.properties), and since CI runs SF from inside portal, all those enabled checks are in effect. I use a script to copy over all those enabled checks when I run SF locally, but even then it still doesn't always get the same results (like in this situation, I don't get all the failures).

You can at least see the [full output](https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/42//consoleText) from CI's SF run :/. Not really as helpful as it could be, tho.

**Comment by ethanbustad** [comment]
@ZoltanTakacs , I lied. My script did catch the other errors, it just fixed them automatically.

We should maybe just enable all the SF checks inside our repo, too, since we need to pass them in all our PRs anyway...

I'll start up a convo on our slack channel discussing this idea.

**Comment by ZoltanTakacs** [comment]
Thank you very much @ethanbustad for all of these details, I hope we can enable all of these checks in the commerce repo as well. :) 👍

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by ZoltanTakacs** [comment]
Hey @ethanbustad ,

I've added the the missing properties to `source-formatter.properties` and modified almost all of the remaining sf issues, but we still have 3 beside the infinite loop that I cannot reproduce on local env.. Also these errors on CI are not helpful, maybe it just me, but I don't know what to do with them.. :/ 🤷‍♂️  

Do we need to include other props as well?

Thanks for you help in advance

**Comment by ZoltanTakacs** [comment]
Hi @hhuijser when you have time, could you please help us finding the root cause of the infinite loop in the source formatter? Thanks in advance!

**Comment by ethanbustad** [comment]
@ZoltanTakacs yeah, the `expected <...> but was <...>` errors are _really_ hard to read. But they are understandable if you try hard :). I usually open up the `consoleText` in jenkins, copy over each failure separately into a text editor, separate out the `expected <...>` from the `but was <...>`, and then run a diff tool to find the difference.

It may help to include other props, too, but I'm not really sure :/. I think what you've done is all I've figured out how to do to make local results more like CI.

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:close

**Comment by ZoltanTakacs** [comment]
Resent on https://github.com/liferay/com-liferay-commerce/pull/273

**Pull request closed without merging**
