### PR TITLE
COMMERCE-2362 Just show options with a sku connected

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
looks like probably a CI error

**Comment by yichenroy** [comment]
@ethanbustad 
The failure seems to be coming from the dxp app merge in portal 7.1.x.
> Incorrect "project.path.prefix" in modules/dxp/apps/commerce/gradle.properties expected:<:[dxp]:apps:commerce> but was:<:[private]:apps:commerce>

source: https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/192/testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts/

The file in portal 7.1.x:
https://github.com/liferay/liferay-portal-ee/blob/7.1.x/modules/dxp/apps/commerce/gradle.properties#L6

**Comment by marco-leo** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Pull request merged**
