### PR TITLE
COMMERCE-1065 | 7.1.x-next

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
[Commerce API Scrum board](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=3928)
----
Ticket: https://issues.liferay.com/browse/COMMERCE-1065

/cc @matijapetanjek

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Review by marco-leo — APPROVED** [review]

**Comment by marco-leo** [comment]
@ZoltanTakacs looks good. just fix SF and will merge it

**Comment by ZoltanTakacs** [comment]
ci:test
@marco-leo I rebased and pushed the fix for the SF error. Thanks!

**Comment by ZoltanTakacs** [comment]
Hi @matijapetanjek as per our discussion on the Daily Stand-up, please also add the "callbackUrl" column for the service.
I'm closing this for the meanwhile.

Thanks in advance!

**Pull request closed without merging**
