### PR TITLE
COMMERCE-600 some fixes + authorize net payment method

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by ethanbustad** [comment]
Fixing these errors in upstream.

**Comment by ethanbustad** [comment]
ci:test
All these errors should be fixed now.

**Comment by ethanbustad** [comment]
@luca-pellizzon @marco-leo resent to https://github.com/liferay/com-liferay-commerce/pull/404.

**Pull request closed without merging**
