### PR TITLE
COMMERCE-639

### PR DESCRIPTION
**Pull request by alessiorendina**
https://issues.liferay.com/browse/COMMERCE-639

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by ethanbustad** [comment]
Uggh, failure caused by https://github.com/liferay/liferay-portal/commit/e36f57933b5dbdd8c6308925419d9a43c1638c54, since we rely on the `com.liferay.portal.kernel.portlet` package in `commerce-product-definitions-web`. Not sure the right fix here. Will investigate.

**Comment by ethanbustad** [comment]
Should be fixed once this is merged: https://github.com/liferay/com-liferay-commerce/pull/165.

**Comment by ethanbustad** [comment]
ci:test

**Pull request merged**
