### PR TITLE
COMMERCE-149 Fix Terms of Use panel

### PR DESCRIPTION
**Pull request by alecsloan**
Let me know if you have any questions.

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
Should be fixed by https://github.com/liferay/com-liferay-commerce/pull/817.

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
#817 merged now.

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
(Resent to https://github.com/liferay/com-liferay-commerce/pull/821.)

**Pull request closed without merging**
