### PR TITLE
COMMERCE-1661 check if order is approved, if not redirect to order de…

### PR DESCRIPTION
**Pull request by luca-pellizzon**
…tails

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
merged in https://github.com/liferay/com-liferay-commerce/pull/1255

**Pull request closed without merging**
