### PR TITLE
LRQA-48109 | 7.1.x-next

### PR DESCRIPTION
**Pull request by iovaneale**
https://issues.liferay.com/browse/LRQA-48109

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
@marco-leo could you please help me understanding this failure?

**Comment by iovaneale** [comment]
@ethanbustad, is this what you talked about in the slack channel?

`>   class      com.liferay.portal.kernel.util.LocalizationUtil
     [exec] 		-   method     populateLocalizationMap(java.util.Map,java.lang.String,long)
     [exec] 			-   access     static
     [exec] 			-   return     java.util.Map
     [exec] 	>   interface  com.liferay.portal.kernel.util.Localization
     [exec] 		-   method     populateLocalizationMap(java.util.Map,java.lang.String,long)
     [exec] 			-   access     abstract
     [exec] 			-   return     java.util.Map
     [exec] 	+   version    8.16.0
     [exec] 	-   version    8.17.0
     [exec] * com.liferay.portal.kernel.workflow                 MAJOR      7.3.0      7.4.0      8.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.kernel.workflow.WorkflowInstanceManagerUtil
     [exec] 		-   method     search(long,java.lang.Long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Boolean,int,int,com.liferay.portal.kernel.util.OrderByComparator)
     [exec] 			-   access     static
     [exec] 			-   return     java.util.List
     [exec] 		-   method     searchCount(long,java.lang.Long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Boolean)
     [exec] 			-   access     static
     [exec] 			-   return     int
     [exec] 	>   interface  com.liferay.portal.kernel.workflow.WorkflowInstanceManager
     [exec] 		-   method     search(long,java.lang.Long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Boolean,int,int,com.liferay.portal.kernel.util.OrderByComparator)
     [exec] 			-   return     java.util.List
     [exec] 		-   method     searchCount(long,java.lang.Long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Boolean)
     [exec] 			-   return     int
     [exec] 	+   version    7.3.0
     [exec] 	-   version    7.4.0
     [exec] [Baseline Warning] Bundle Version Change Recommended: 4.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal-7.1.x/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/3.60.0/2f64f819a5e93099c0f168f06caa2bf867ce6956/com.liferay.portal.kernel-3.60.0.jar`

**Comment by ethanbustad** [comment]
@iovaneale, no, but it looks like that's a portal issue that we'll just have to wait to be fixed.

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
@marco-leo it failed again because of the same issue. @ethanbustad, the error is different from the one thrown yesterday.

**Comment by iovaneale** [comment]
ciçtest

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
@marco-leo, I've pushed an Auto SF, but it seems that was not the problem. :(

**Comment by ethanbustad** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test:bundle

**Comment by iovaneale** [comment]
ci:test:bundle

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Pull request closed without merging**
