### PR TITLE
COMMERCE-2050 COMMERCE-2276 Fixes from Fabio

### PR DESCRIPTION
**Pull request by ethanbustad**

### CODE REVIEW

**Comment by ethanbustad** [comment]
See https://github.com/liferay/com-liferay-commerce/pull/1591 and https://github.com/liferay/com-liferay-commerce/pull/1544.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@FabioDiegoMastrorilli I'm thrilled to hear we're able to use more linting tools in frontend now! 🙌 

Keep in mind these tools probably won't fix everything. e.g. filenames being dash-delimited vs. underscore-delimited (see [COMMERCE-1133](https://issues.liferay.com/browse/COMMERCE-1133) -- this has been a long time in the works :) ). I see we've got this issue throughout Minium (and a couple other modules) still, so I'm ok not insisting that it's fixed in this PR, but _please please please_ keep this in mind going forward, and it would be wonderful if somebody could send a pull fixing it all over, once and for all.

**Comment by ethanbustad** [comment]
@marco-leo merging to fix CI issues. I'll keep this on a list of tickets merged for your review, in case you want it later.

**Comment by marco-leo** [comment]
@ethanbustad @FabioDiegoMastrorilli there is a lot of renaming and code review of the tag implementation to do in this pull.  I prefer to have a pr just for the fix of the bug and don't mix with new code. Now is a bit messy and we must review all that code before 2.0.7 to avoid a bump in the baseline

**Comment by ethanbustad** [comment]
@marco-leo this PR passed tests without baseline changes at least. But I do agree this isn't ideal :(, and this is bigger changes than I wanted to merge. But I think it's worth it to get proper test results on the rest of the open PRs. Sorry :/

**Comment by marco-leo** [comment]
@ethanbustad, not a big issue, we have to review all of that code, that's it :) I was just planing after 2.0.7 that's it

**Pull request merged**
