### PR TITLE
COMMERCE-1857 dependency version requirement removed on commerce fron…

### PR DESCRIPTION
**Pull request by fabio-d-m**
…tend taglib

@marco-leo now you owe me a beer

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
@FabioDiegoMastrorilli please fix the source formatter issues :D

**Comment by fabio-d-m** [comment]
@marco-leo pr updated

**Comment by alecsloan** [comment]
ci:test

**Pull request merged**
