### PR TITLE
COMMERCE-553 Commerce media servlet and URL resolver (2)

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-553

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
@alecsloan @ethanbustad good job guys!!

**Pull request merged**
