### PR TITLE
LRCI-801 Deploy Commerce like other modules

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/LRCI-801

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@brianwulbern

**Comment by brianwulbern** [comment]
CI Infra is testing a fix for the `InvalidUserDataException`: https://github.com/yichenroy/com-liferay-commerce/pull/34

**Comment by brianwulbern** [comment]
ci:test

@ethanbustad @yichenroy trying this one again since https://github.com/yichenroy/com-liferay-commerce/pull/34 should be resolved by https://github.com/pyoo47/liferay-jenkins-ee/pull/1293

**Comment by yichenroy** [comment]
ci:test
Failure due to network outage.

**Comment by ethanbustad** [comment]
ci:test
failure looks like network flakiness

**Pull request merged**
