### PR TITLE
Commerce 2327 incorrect required field name

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
@ethanbustad @marco-leo It seems fine to me this PR

**Comment by marco-leo** [comment]
@igorbeslic @andrea-ale-sbarra  please update swagherhub

**Comment by igorbeslic** [comment]
Andrea had updated it before PR was sent 🥇

**Pull request merged**
