### PR TITLE
COMMERCE-619 | COMMERCE-620 | COMMERCE-621 | COMMERCE-623

### PR DESCRIPTION
**Pull request by alessiorendina**
/cc @marco-leo @luca-pellizzon

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:retest

**Comment by alessiorendina** [comment]
ci:retest

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
Most of the SF failures are due to `7.1.x-next` not having the SF fixes I just committed to `7.1.x`. @marco-leo, are you planning on updating `7.1.x-next` to the latest state of `7.1.x`? (If so, there'll be a rebase conflict, and the line number will have to be set to `124` in the resolution.)

**Comment by marco-leo** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:retest

**Pull request closed without merging**
