### PR TITLE
COMMERCE-697

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
Hey @Commando18 error 2 looks like a sorting issue -- `setNextIterationDate` should come before `setStartDate`. I think [this whole block](https://github.com/liferay/com-liferay-commerce/pull/215/files#diff-8f41c3614db1afe73adfb6173284744eR241) should be sorted alphabetically (or insert an extra newline to indicate where it shouldn't be sorted).

The first issue is that the `end-after=End After` key in `Language.properties` should be removed. It must not be used any more.

**Comment by alessiorendina** [comment]
ci:retest

**Comment by alessiorendina** [comment]
@ethanbustad Thanks!

**Comment by alessiorendina** [comment]
ci:retest

**Comment by alessiorendina** [comment]
ci:retest

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:retest

**Comment by jpince** [comment]
@pyoo47 not sure if this is trying to fetch a commit from 7.1.x upstream or commerce/7.1.x-next. Not sure if this is network-related.
```
[beanshell] java.lang.RuntimeException: Unable to create local branch 7.1.x-next at 6ed9d5b7433166666f3e129bbf631bbec960ddbd
[beanshell] fatal: Not a valid branch point: '6ed9d5b7433166666f3e129bbf631bbec960ddbd'.
```

**Comment by jpince** [comment]
ci:test

**Comment by yichenroy** [comment]
@Commando18 
The 7.1.x-next branch needs to be sync'd between com-liferay-commerce and com-liferay-commerce-private. The 7.1.x upstream sha `6ed9d5b7433166666f3e129bbf631bbec960ddbd` only exists in com-liferay-commerce right now, so CI fails. 

Our servers only store the -private subrepositories so the branches in the public subrepository will have to be in sync with the private subrepository.

cc @jpince @pyoo47

**Comment by pyoo47** [comment]
ci:test:a16f94b6f0f7ad62a4100ddcdad73a741721275a

Forcing CI to use the latest SHA in com-liferay-commerce-private.

**Comment by yichenroy** [comment]
We plan to make the change so we fetch the latest upstream sha from the private subrepository instead to mitigate the issue. In the mean time the branches can either be sync'd between the repos, or an upstream sha from the private subrepository can be manually provided like this 
`ci:test:[upstream sha from private repository]`

Please follow this ticket for the progress on the change: https://issues.liferay.com/browse/LRQA-44482

**Comment by ethanbustad** [comment]
Sorry guys -- so far sync'ing the `7.1.x-next` branch between the repos is manual. Just sync'd them, so we'll be ok without the workaround again for the moment.

**Comment by alessiorendina** [comment]
ci:test:a16f94b6f0f7ad62a4100ddcdad73a741721275a

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test:6dd1f48da81721f07a49065855a9256711a7437c

**Comment by pyoo47** [comment]
ci:test:e863b6e650dd23f919597c289b13b1013975825e

**Comment by pyoo47** [comment]
ci:test:6ed9d5b7433166666f3e129bbf631bbec960ddbd

**Pull request closed without merging**
