### PR TITLE
(From Fabio) Commerce 1985 Fix Discount labels

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
From #1081

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
@marco-leo I fixed the major version increase on currency-api but the one on frontend-taglib looks more complex since methods were removed.

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
Since frontend taglib increased a major version, minium impl doesn't have access to the new attribute. Just needs to switch to a project dependency to gain access.

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by iovaneale** [comment]
ci:test

**Comment by marco-leo** [comment]
This pull does not contain the right fix. Managing this offline

**Pull request closed without merging**
