### PR TITLE
COMMERCE-1056 Call RegionStarters when adding countries manually (from Alessio)

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-1056

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
_sigh_... my bad

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Pull request merged**
