### PR TITLE
LRQA-43110 (from @iovaneale)

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/LRQA-43110
https://issues.liferay.com/browse/LRQA-43343
https://issues.liferay.com/browse/LRQA-43657

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
^ I think these are all test fixes :/

**Comment by iovaneale** [comment]
Yeah! I’m looking at them right now.

**Comment by marco-leo** [comment]
I will start crying in a bit :(

**Comment by ethanbustad** [comment]
Hahaha it's almost 2am. You guys are crazy :)

**Comment by iovaneale** [comment]
So, I would assert that these failures (all the same) are weird.

It seems everything breaks at ```Click#waitForMenuToggleJSClick```. What I don't understand is that this function is supposed to be executed as "else", in case the entry name is not present (I inserted the condition to prevent fluky failures faced in the past). Anyways it should not be considered since the entry name is present, at least standing on local reproduction.

@jpince, have you any idea of why this happens, or just suggest us who can help us on this? Thanks.

In case I will just remove the conditional from the code.

/cc @ethanbustad @marco-leo

**Comment by iovaneale** [comment]
sent to #151

**Comment by brianwulbern** [comment]
@iovaneale, it doesn't look like the if-else logic is the source of the issue - there looks like an issue on the server upon saving a new Commerce User Segment.  The UI looks messed up in some cases (the big X across the screen), and in others, there's `An unexpected system error occurred.` noting a `portal.kernel.search.SearchException` taking down the server.

If you're not seeing this error locally, I wonder what kinds of differences there may be between the Jenkins environment and your local one.

**Pull request closed without merging**
