### PR TITLE
Commerce 432

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
Hey @luca-pellizzon, I think source-formatter is complaining here because the `view-more=View More` language property is already in portal. Is there a reason we need to duplicate this key (e.g. if we want to translate it differently than portal for some reason)?

**Comment by ethanbustad** [comment]
Just confirmed that `view-more` is still translated properly without the new lang key. Testing CI without the lang changes here: https://github.com/ethanbustad/com-liferay-commerce/pull/4.

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:stop

**Pull request merged**
