### PR TITLE
COMMERCE-1237 Refactor Order APIs

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
@marco-leo This is based on top of #1167 . Please merge it after #1167

**Comment by alessiorendina** [comment]
ci:test

**Comment by marco-leo** [comment]
sent https://github.com/liferay/com-liferay-commerce/pull/1179

**Pull request closed without merging**
