### PR TITLE
Get tests green: 7.1.x-next (3rd attempt)

### PR DESCRIPTION
**Pull request by ethanbustad**

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
@marco-leo not sure what to make of the above results. The setup failure looks like maybe a portal issue, which _may_ have caused the other issues, too. But it is strange that we're getting just a few failures, both in functional and integration tests.
Kicking off a new set of tests -- if these next ones fail in the same way, we may need @iovaneale and @Commando18 to investigate... on first glance it looks like new tests that are failing.

**Comment by marco-leo** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:close
It's been merged w/ https://github.com/liferay/com-liferay-commerce/pull/287

**Pull request closed without merging**
