### PR TITLE
COMMERCE-1621 Liferay 7.2 compatibility!!

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-1621

This works on 7.1.
This works on 7.2 except for a couple frontend issues.

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
I think this won't pass until the changes I made to 7.1 are published, which apparently hasn't been done yet....

**Comment by ethanbustad** [comment]
ci:test
`com.liferay.portal.template.soy.api` version 1.3.0 is now available on Nexus

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/tree/7.2.x

**Pull request closed without merging**
