### PR TITLE
Speedwell (from Gianmarco)

### PR DESCRIPTION
**Pull request by alecsloan**
#1260

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by yichenroy** [comment]
Hi @alecsloan,
Has there been changes to how the "baseline"  task works in Commerce 7.1.x-next recently? 
I noticed that the task is now expecting a bundle to be present since it tries to look for this directory:
`java.nio.file.NoSuchFileException: /opt/dev/projects/github/liferay-portal-7.1.x/bundles/osgi`

This looks like a recent change since it wasn't an issue 2 days ago here:
https://github.com/liferay/com-liferay-commerce/pull/1245

I replicated the above passing pullrequest with up-to-date upstream 7.1.x-next here but it failed for the same file not found error:
https://github.com/yichenroy/com-liferay-commerce/pull/28

It looks like all 7.1.x-next pullrequests will run into this issue, there is no bundle present during the validation stage of pull request test.

**Comment by alecsloan** [comment]
Hey @yichenroy Thanks for looking into it, not that I'm aware of. ~I just tried deploying the theme and gulp failed so maybe that's the issue, but I don't see any indications of that in the CI failure~. Also interesting that the failure occurs on a completely different module than what this RP is touching.

Edit: Looks like this is a build issue not CI. I can't even deploy modules locally now because that error is happening. Maybe @petershin and @hhuijser should be looped in?

**Comment by alecsloan** [comment]
ci:test

**Comment by yichenroy** [comment]
@alecsloan 
The pr test for subrepository-semantic-versioning-jdk8 executes a "baseline" gradle task on Commerce as a whole: https://github.com/liferay/liferay-portal-ee/blob/5b7ff8a4a8c885c892597e7d18de9bd904ee4d4e/build-test-batch.xml#L5374

It'd be beneficial to confirm if there were functional changes to how "baseline" works in Commerce.

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
force push reflects rebase and combining of commits that were in a row with the same messages.

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:stop

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/1400

**Pull request closed without merging**
