### PR TITLE
COMMERCE-1960 Make sure we're using the localized index fildname

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:stop

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]
Beautiful.

**Comment by marco-leo** [comment]
@alecsloan we can review the fields we are indexing in the CPDefinitionIndexer and check witch one we do use for real, so we can clean a bit, @riccardo-ferrari

**Comment by alecsloan** [comment]
Si Signore, Just CPDefinitionIndexer? @marco-leo

**Pull request merged**
