### PR TITLE
COMMERCE-828

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
[Commerce API Scrum board](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=3928)
----
Ticket: https://issues.liferay.com/browse/COMMERCE-813

/cc @igorbeslic

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by igorbeslic** [comment]
@ZoltanTakacs great job!

**Comment by ZoltanTakacs** [comment]
Thanks @igorbeslic , the credit goes to you :) 👍 💯

**Comment by marco-leo** [comment]
@ZoltanTakacs @igorbeslic Good job guys!

**Pull request merged**
