### PR TITLE
COMMERCE-1178 Render command should be plural

### PR DESCRIPTION
**Pull request by alecsloan**
Let me know if you have any questions.

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
force push reflects commit rewording

**Review by ethanbustad — APPROVED** [review]

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Pull request merged**
