### PR TITLE
Commerce 2035 orders

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
Now shipping address, billing address and order items are managed as nested fields

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]
Same question here -- do we need to `gw buildREST`?

**Comment by ethanbustad** [comment]
ci:test
above failure is the same ECB connection issue

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
Hi @ethanbustad , you were right buildREST made some changes, thank you!

**Pull request merged**
