### PR TITLE
COMMERCE-1463 Fix licensing issues/ambiguities

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-1463

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@marco-leo this is ready to merge to resolve https://issues.liferay.com/browse/COMMERCE-1463

**Comment by marco-leo** [comment]
@ethanbustad please update the swaggerhub as well

**Comment by ethanbustad** [comment]
Hey @marco-leo, I don't know how to do that.... Can you point me in the right direction?

**Pull request merged**
