### PR TITLE
COMMERCE-727 Fixed allowed quantities

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:retest

**Comment by alessiorendina** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:test:6dd1f48da81721f07a49065855a9256711a7437c

com-liferay-commerce and com-liferay-commerce-private are out of sync. Currently, the GitHub hook assumes that they are always in sync so it uses the latest commit from com-liferay-commerce when attempting to rebase the pull request with com-liferay-commerce-private. Since the latest commit in com-liferay-commerce does not yet exist in com-liferay-commerce-private, the rebase fails. We are working to modify the GitHub hook behavior to use the latest commit from com-liferay-commerce-private but until that is fixed, you will have to manually indicate the latest commit from com-liferay-commerce-private to ensure that the rebase doesn't fail.

**Pull request merged**
