### PR TITLE
COMMERCE-2425 Migrate private modules (from Riccardo)

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-2425

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test
🤞

**Comment by ethanbustad** [comment]
ci:test
Maybe a fluke?

**Comment by yichenroy** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
I think SF will still fail, but with a lot less errors. Hopefully that makes it easier to see what's going on. We may require SF changes to make things work for us.

**Comment by ethanbustad** [comment]
ci:test
bleh, now for a more helpful result

**Comment by riccardo-ferrari** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@hhuijser @petershin can you guys take a look at this latest failure? I think I've fixed as much as I can here in the subrepo.
* SF wants us to use a project dependency for the spring extender and taglib modules, but I don't think that's possible in the subrepo
* It wants us to use version `default` for things like `com.liferay.taglib.util`, but I think that only makes sense when the deployment is part of portal

That's all the errors I can discern so far from this output...

**Comment by hhuijser** [comment]
@ethanbustad, let's suppress this check for all files in `commerce` using `source-formatter-suppressions.xml`

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
Maybe today?

**Comment by ethanbustad** [comment]
ci:test
Trying one more time. If `MissingDeprecatedCheck` fails again I'll just ignore it

**Comment by marco-leo** [comment]
@ethanbustad we can actually take advantage of this major bump and remove those deprecated methods

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
@hhuijser looks like SF wants us to do something that won't compile in 7.1

**Comment by ethanbustad** [comment]
ci:test
seriously.... this error's gotta go away eventually....

**Comment by marco-leo** [comment]
@ethanbustad @jpince @brianchandotcom  test are failing for not related error, after 10 days trying we need to merge this pull to start the subrepo deprecation, but we still need to make sure tests pass before we do it

**Pull request merged**
