### PR TITLE
COMMERCE-1578 Added minium-wrapper to portal_normal.ftl

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
@gianmarcobrunialti please update this pull fixing the SF

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by marco-leo** [comment]
Hi @gianmarcobrunialti  I don't see the changes requested from Corbin in the issue, are we respecting this? https://portal.liferay.dev/docs/6-2/tutorials/-/knowledge_base/t/the-html-structure-of-portalnormal-ftl

**Comment by gianmarcobrunialti** [comment]
@marco-leo This is no more needed.

**Pull request closed without merging**
