### PR TITLE
COMMERCE-2368 Hold address info for placed orders on their model (from Alec)

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-2368

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
@alecsloan  Do I already tell you how much I love Integration tests? :)

**Comment by alecsloan** [comment]
I wasn't able to get these test failures locally....

rebased and sent to #1807

**Comment by ethanbustad** [comment]
Forwarded to https://github.com/liferay/com-liferay-commerce/pull/1807.

**Pull request closed without merging**
