### PR TITLE
COMMERCE-774 Account services

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by marco-leo** [comment]
@ethanbustad Please help us!!!! Please help us!!! Please help us :) . 

I will merge this pull as i need to publish snapshot for private modules

**Comment by ethanbustad** [comment]
@marco-leo kk, taking a look

**Comment by ethanbustad** [comment]
I think most of the issues were fixed in https://github.com/liferay/com-liferay-commerce/commit/143620fef40df2595a9e7fa8908394a0bfe3bdb6.
The last one should be fixed in https://github.com/liferay/com-liferay-commerce/pull/346.

**Pull request merged**
