### PR TITLE
COMMERCE-737 Reduce APIO dependencies

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-737

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
## Update ##

Judging from the integration test result which includes end-to-end API testing, it passed  -> https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/65/AXIS_VARIABLE=0,label_exp=!master/testReport/com.liferay.commerce.data.integration.apio.resource.test/

nonetheless, the problem is more complex when we adding CE/DXP as well to the matrix..
just tried without the headless APIs + commerce 1.0.1 + the newly compiled bundles for
```
com.liferay.commerce.data.integration.apio.api.jar
com.liferay.commerce.data.integration.apio.impl.jar
```

and the result was ->
```
2018-11-30 10:53:00.821 INFO  [main][LPKGBundleTrackerCustomizer:511] Disabled Liferay Commerce - API:file:/D:/Temp/liferay-ce-portal-7.1.1-ga2/osgi/marketplace/Liferay Commerce - API.lpkg!/com.liferay.commerce.data.integration.apio.api-1.0.1.jar
2018-11-30 10:53:00.829 INFO  [main][LPKGBundleTrackerCustomizer:511] Disabled Liferay Commerce - Impl:file:/D:/Temp/liferay-ce-portal-7.1.1-ga2/osgi/marketplace/Liferay Commerce - Impl.lpkg!/com.liferay.commerce.data.integration.apio.impl-1.0.1.jar
2018-11-30 10:53:00.865 INFO  [main][ModuleFrameworkImpl:1592] Started initial bundles
2018-11-30 10:53:00.866 INFO  [main][ModuleFrameworkImpl:1627] Starting dynamic bundles
2018-11-30 10:53:19.207 ERROR [Framework Event Dispatcher: Equinox Container: f3c47d0c-3331-4076-8637-0148723f031e][com_liferay_commerce_data_integration_apio_impl:97] FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: com.liferay.commerce.data.integration.apio.impl [1045]_  Unresolved requirement: Import-Package: com.liferay.portal.apio.idempotent; version="[1.0.0,2.0.0)"_ [Sanitized]
        at org.eclipse.osgi.container.Module.start(Module.java:444)
...
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
2018-11-30 10:53:19.213 ERROR [main][ModuleFrameworkImpl:1704] Unable to start bundle com.liferay.commerce.data.integration.apio.impl
org.osgi.framework.BundleException: Could not resolve module: com.liferay.commerce.data.integration.apio.impl [1045]_  Unresolved requirement: Import-Package: com.liferay.portal.apio.idempotent; version="[1.0.0,2.0.0)"_ [Sanitized]
        at org.eclipse.osgi.container.Module.start(Module.java:444)
...
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
        at com.liferay.portal.bootstrap.ModuleFrameworkImpl._startDynamicBundles(ModuleFrameworkImpl.java:1701)
...
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4643)
...
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
2018-11-30 10:53:19.395 INFO  [main][ModuleFrameworkImpl:1716] Started dynamic bundles
2018-11-30 10:53:19.396 INFO  [main][ModuleFrameworkImpl:413] Navigate to Control Panel > Configuration > Gogo Shell and enter "lb" to see all bundles
```

and checked the modification and saw that we `played` w/ the `deployDependencies` so I also need to deploy:
```
com.liferay.site.apio.api.jar
com.liferay.portal.apio.impl.jar
com.liferay.portal.apio.api.jar
com.liferay.person.apio.api.jar
com.liferay.folder.apio.api.jar
```

then the CE/DXP portal started flawlessly until you've tried to reach the end-point:
e.g. http://localhost:8080/o/api/p/web-sites/36016/commerce-product-definition

and got a beautiful stack-trace: (edited)
```
018-11-30 12:05:16.762 ERROR [http-nio-8080-exec-2][JAXRSUtils:83] Problem with writing the data, class com.liferay.apio.architect.functional.Try$Success, ContentType: application/octet-stream
2018-11-30 12:05:16.784 WARN  [http-nio-8080-exec-2][PhaseInterceptorChain:88] Interceptor for {http://endpoint.internal.architect.apio.liferay.com/}RootEndpointImpl has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: com.liferay.person.apio.architect.identifier.PersonIdentifier could not be found in the function
        at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleWriteException(JAXRSOutInterceptor.java:396)
...
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.liferay.apio.architect.internal.wiring.osgi.error.ApioDeveloperError$IdentifierNameNotFoundInPathFunction: com.liferay.person.apio.architect.identifier.PersonIdentifier could not be found in the function
        at com.liferay.apio.architect.internal.wiring.osgi.manager.representable.RepresentableManagerImpl.lambda$_getNameOrFail$4(RepresentableManagerImpl.java:187)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.liferay.apio.architect.internal.wiring.osgi.manager.representable.RepresentableManagerImpl._getNameOrFail(RepresentableManagerImpl.java:185)
        at com.liferay.apio.architect.internal.representor.BaseRepresentorImpl.lambda$addRelatedModel$2(BaseRepresentorImpl.java:433)
        at com.liferay.apio.architect.internal.related.RelatedModelImpl.getIdentifierName(RelatedModelImpl.java:58)
        at com.liferay.apio.architect.internal.writer.FieldsWriter.writeRelatedModel(FieldsWriter.java:566)
        at com.liferay.apio.architect.internal.writer.FieldsWriter.writeRelatedModel(FieldsWriter.java:496)
        at com.liferay.apio.architect.internal.writer.FieldsWriter.lambda$writeRelatedModels$20(FieldsWriter.java:600)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.liferay.apio.architect.internal.writer.FieldsWriter.writeRelatedModels(FieldsWriter.java:599)
        at com.liferay.apio.architect.internal.writer.PageWriter._writeItem(PageWriter.java:472)
        at com.liferay.apio.architect.internal.writer.PageWriter.lambda$write$0(PageWriter.java:109)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
        at com.liferay.apio.architect.internal.writer.PageWriter.write(PageWriter.java:108)
        at com.liferay.apio.architect.internal.jaxrs.json.writer.PageMessageBodyWriter.write(PageMessageBodyWriter.java:107)
        at com.liferay.apio.architect.internal.jaxrs.json.writer.PageMessageBodyWriter.write(PageMessageBodyWriter.java:52)
        at com.liferay.apio.architect.internal.jaxrs.json.writer.base.BaseMessageBodyWriter.writeTo(BaseMessageBodyWriter.java:151)
        at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1391)
        at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:246)
        ... 86 more
```

 @marco-leo do not merge this yet.

**Review by ZoltanTakacs — CHANGES_REQUESTED** [review]
Please see https://github.com/liferay/com-liferay-commerce/pull/269#issuecomment-443644554

**Comment by ethanbustad** [comment]
Will send a new PR once we have everything resolved.

**Pull request closed without merging**
