### PR TITLE
COMMERCE-576 Fix paypal submission failure

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-576

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
Failed with the same error as https://github.com/liferay/com-liferay-commerce/pull/69#issuecomment-412965057. Jenkins just never got back to github. @michaelhashimoto @kenjiheigel @yichenroy  @jpince 

Isn't this the same error as https://issues.liferay.com/browse/LRQA-42798, which should be fixed?

**Comment by yichenroy** [comment]
@ethanbustad 
It was tested here which contained the changes from https://issues.liferay.com/browse/LRQA-42798:
https://github.com/yichenroy/com-liferay-commerce/pull/2

QA Engineering will continue investigating this issue.

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
@ethanbustad The change should be reflected now, due to the way subrepository pullrequests work, the changes in liferay-portal upstream is not reflected until a new bundle has been built in the upstream, so the same issue should not appear anymore.

There was a spontaneous network outage that affected all pullrequests running in the last hour so some test results may appear as "aborted."

**Comment by yichenroy** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:retest

**Comment by ethanbustad** [comment]
Not able to replicate these unit test failures locally.... and the first failure looks like maybe a CI issue? Not sure. Going to try retesting one more time. :crossed_fingers:

**Comment by ethanbustad** [comment]
ci:retest

**Comment by ethanbustad** [comment]
@jpince for the life of me, I cannot replicate this locally. Any words of wisdom you can throw my way?

**Comment by jpince** [comment]
@ethanbustad the only thing I can possibly think of is maybe `CommercePriceFormatterTest > testFormatBigDecimal` isn't properly cleaning up after itself? But maybe you're already running that test in your local runs. If that's not it, I would say ask Shuyang to see if it's something that's only reproducible in CI.

**Comment by ethanbustad** [comment]
Most likely caused by https://loop.liferay.com/home/-/loop/feed/13143365. Will test this solution locally.

**Comment by ethanbustad** [comment]
ci:retest

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@marco-leo just pushed an update, let me know what you think

**Comment by marco-leo** [comment]
ci:retest

**Comment by marco-leo** [comment]
@ethanbustad the pull looks good.

**Comment by marco-leo** [comment]
Thanks @ethanbustad

**Pull request merged**
