### PR TITLE
COMMERCE-686 add to cart button strings i18n

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
Tested behaviour:
Screenshot 2019-05-15 at 10 47 41

Screenshot 2019-05-15 at 10 51 03

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by gianmarcobrunialti** [comment]
Tests failing with a `ConnectException`. Waiting to retrigger.

**Comment by ethanbustad** [comment]
@gianmarcobrunialti yeah, should be because of the arquillian upgrade. I think we just need to wait for the CI bundles to catch up (start using the new version), and then things should pass again.

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by gianmarcobrunialti** [comment]
Tests had finally passed in the last batch, but still the failure was reported, so I retriggered them. What is this due to?

**Comment by ethanbustad** [comment]
Hey @gianmarcobrunialti, I think the failure is due to the test bundles not being up-to-date with a dependency change we just made. So don't worry about it -- for now I think we'll just ignore it and look for it to resolve itself in the next day or so. If it doesn't, I'll look into it more in depth.

Marco let me know he wants this PR in ASAP, so I'll make sure it gets in today. Thanks for getting it ironed out!

**Comment by ethanbustad** [comment]
Sent to https://github.com/liferay/com-liferay-commerce/pull/892 so we can merge directly into 7.1.x (with a couple small changes)

**Pull request closed without merging**
