### PR TITLE
LRQA-43110-2 | 7.1.x

### PR DESCRIPTION
**Pull request by iovaneale**

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
On `Click#mouseDownMouseUp` of the Save button to create a new Commerce User Segment, console is getting this:
```
 02:21:43,497 ERROR [http-nio-8080-exec-8][MainServlet:1212] com.liferay.portal.kernel.events.ActionException: com.liferay.portal.kernel.search.SearchException: java.lang.RuntimeException: com.liferay.portal.kernel.search.SearchException: all shards failed
     [exec] com.liferay.portal.kernel.events.ActionException: com.liferay.portal.kernel.search.SearchException: java.lang.RuntimeException: com.liferay.portal.kernel.search.SearchException: all shards failed
     [exec] 	at com.liferay.commerce.product.internal.events.CPRulesPreAction.run(CPRulesPreAction.java:61)
     [exec] 	at com.liferay.portal.kernel.events.Action.processLifecycleEvent(Action.java:34)
     [exec] 	at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:98)
     [exec] 	at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:60)
```

@iovaneale do you get that error locally?

**Comment by iovaneale** [comment]
@brianwulbern No, I don't get this error locally. The build is successful for all the failing tests in this PR

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:stop

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by ethanbustad** [comment]
ci:test:relevant curious whether the results are consistent....

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:stop

**Comment by iovaneale** [comment]
ci:test

**Comment by ethanbustad** [comment]
@yichenroy do you know if these tests are still queued or running? Everything I see seems to indicate the tests are done, but we still don't have functional test results....

**Comment by yichenroy** [comment]
@ethanbustad 
The test failed out because we were accidentally exceeding the github API limit
`"  [exec]    message": "API rate limit exceeded for user ID 4502793.",
     [exec]   "documentation_url": "https://developer.github.com/v3/#rate-limiting"`

We are working on the fix, for now this will have to be retested.

**Comment by yichenroy** [comment]
ci:test

**Comment by ethanbustad** [comment]
@yichenroy thanks!

**Comment by marco-leo** [comment]
ci:stop

**Pull request merged**
