### PR TITLE
LRQA-43110 | 7.1.x

### PR DESCRIPTION
**Pull request by iovaneale**
https://issues.liferay.com/browse/LRQA-43110

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
@ethanbustad, this is the pull where I updated test.batch.names. Can you take a look?

**Comment by ethanbustad** [comment]
@iovaneale trying out a change here: https://github.com/liferay/com-liferay-commerce/pull/90.

**Comment by ethanbustad** [comment]
Merged #90, so closing this PR (for now at least).

**Pull request closed without merging**
