### PR TITLE
Commerce 2268

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
@marco-leo , should work fine this time.

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/1554

**Pull request closed without merging**
