### PR TITLE
Pricelist (From Luca)

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
Rebased from #997 per Marco's request

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by alecsloan** [comment]
@luca-pellizzon can you take this ticket back over?

**Pull request closed without merging**
