### PR TITLE
COMMERCE-1953 fixed module dependency on soy template renderer

### PR DESCRIPTION
**Pull request by fabio-d-m**

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@FabioDiegoMastrorilli looks like we need to use a newer dependency in order to have access to the `useNamespace` attribute in `template-renderer`.

**Comment by fabio-d-m** [comment]
Hi @ethanbustad! @alecsloan  is updating it https://github.com/liferay/com-liferay-commerce/pull/1392

**Comment by marco-leo** [comment]
see https://github.com/liferay/com-liferay-commerce/pull/1392#issuecomment-532220946

**Pull request closed without merging**
