### PR TITLE
COMMERCE-1069 | 7.1.x-next

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
[Commerce API Scrum board](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=3928)
----
Ticket: https://issues.liferay.com/browse/COMMERCE-1069

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
updated 7.1.x-next in private

**Pull request merged**
