### PR TITLE
COMMERCE-2294 Fix DDM backend usage for 7.1 and 7.2

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-2294

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
Included in https://github.com/liferay/com-liferay-commerce/pull/1719

**Pull request closed without merging**
