### PR TITLE
EMP-27 Apply Order by DESC in orders finder custom sql

### PR DESCRIPTION
**Pull request by NaderJafari**
Apply Order by DESC in finder custom sql

### CODE REVIEW

**Comment by NaderJafari** [comment]
ci:test

**Comment by NaderJafari** [comment]
ci:test

**Comment by ethanbustad** [comment]
@naderjafari CI won't initiate unless the sender is part of the Liferay organization, so don't worry about the tests for now :)

**Comment by NaderJafari** [comment]
> 
> 
> @naderjafari CI won't initiate unless the sender is part of the Liferay organization, so don't worry about the tests for now :)

Thank you :)

**Pull request closed without merging**
