### PR TITLE
COMMERCE-718 Refactor commerce warehouses importer

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:d26aacd923882d29c47d696a57bf165ff36aa352

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
Updated 7.1.x-next branch in private repo.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
Updated private repo.

**Comment by ethanbustad** [comment]
@marco-leo the only failing test here is the bad functional test, so I think we can treat this PR as "passing".

**Pull request merged**
