### PR TITLE
COMMERCE-1291 fix extra padding

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by marco-leo** [comment]
@gianmarcobrunialti did u test if this affect mobile or RTL support?

**Comment by gianmarcobrunialti** [comment]
@marco-leo Mobile and responsive design in general doesn't get affected. In the sense that the previous behaviour is preserved (with the only padding change). The same goes for RTL. Counterchecked with @gcmznt

**Comment by marco-leo** [comment]
Thanks @gianmarcobrunialti !  Looks like you did your first contribution to Commerce

**Comment by gianmarcobrunialti** [comment]
Thanks @marco-leo !

**Pull request merged**
