### PR TITLE
COMMERCE-438 Fix user segments and price lists (from @Commando18)

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-438

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@jpince all our pulls just started quickly failing. Have you been seeing this elsewhere?

**Comment by jpince** [comment]
@michaelhashimoto @pyoo47 rsync failure
`rsync: link_stat "/opt/java/jenkins/userContent/bundles/test-portal-acceptance-upstream(7.1.x)/403/git-hash" failed: No such file or directory (2)`

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
@jpince @ethanbustad Seems to be a recurring problem.. I'll open a new ticket to try to figure out why it's been happening. It should fixed again for now.

**Comment by ethanbustad** [comment]
Alright -- thanks, @pyoo47!

**Comment by pyoo47** [comment]
@petershin Could this be a similar problem to what you recently fixed for com-liferay-poshi-runner?

**Comment by petershin** [comment]
@pyoo47 - Its the same issue.  Sent a patch to Brian: https://github.com/brianchandotcom/liferay-portal/pull/62721

**Comment by ethanbustad** [comment]
Thanks @pyoo47 and @petershin!!

**Comment by pyoo47** [comment]
ci:test (Peter Shin's pull request has been merged)

**Comment by pyoo47** [comment]
ci:test (This happened on the com-liferay-poshi-runner subrepo too.. I think it takes a little time after merging before the changes actually get in)

**Comment by pyoo47** [comment]
@petershin Could there be another SF rule gone wrong here? I've retested this twice since BChan merged your pull request and it's still failing.

**Comment by petershin** [comment]
@pyoo47 - The changes need to be backported from `master` to the `7.1.x`.

Sent a backport request to Brian: https://github.com/brianchandotcom/liferay-portal-ee/pull/21561

**Comment by ethanbustad** [comment]
ci:test thanks, @petershin!

**Comment by ethanbustad** [comment]
ci:test

**Comment by pyoo47** [comment]
@petershin Looks like this failed again even after the backport to 7.1.x was merged.

**Comment by ethanbustad** [comment]
@petershin yeah I think it's still failing for us across the board.

Thanks for following up, @pyoo47.

**Comment by petershin** [comment]
@pyoo47 @ethanbustad - Sorry about the constant failures.  The pull below should fix the remaining issues:

https://github.com/brianchandotcom/liferay-portal-ee/pull/21577

I'll ask Hugo to check the subrepos before adding new SF checks.

**Comment by ethanbustad** [comment]
Thanks, @petershin!

**Pull request merged**
