### PR TITLE
COMMERCE-2261 fix commerce payment engine test

### PR DESCRIPTION
**Pull request by riccardo-alberti**
To be merged after #1604

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test

**Comment by riccardo-alberti** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by riccardo-alberti** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by riccardo-alberti** [comment]
ci:test

**Comment by riccardo-alberti** [comment]
ci:test

**Comment by marco-leo** [comment]
@ethanbustad Merging this, please ask changes if needed

**Pull request merged**
