### PR TITLE
LRQA-43110-2

### PR DESCRIPTION
**Pull request by iovaneale**
https://issues.liferay.com/browse/LRQA-43110
https://issues.liferay.com/browse/LRQA-43343
https://issues.liferay.com/browse/LRQA-43657

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by ethanbustad** [comment]
Fixed SF and sent to https://github.com/liferay/com-liferay-commerce/pull/149.

**Comment by iovaneale** [comment]
Thanks @ethanbustad

**Pull request closed without merging**
