### PR TITLE
COMMERCE-1002 | 7.1.x-next

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
[Commerce API Scrum board](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=3928)
----
Ticket: https://issues.liferay.com/browse/COMMERCE-1002

/cc @matijapetanjek

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by ethanbustad** [comment]
Requires https://github.com/liferay/com-liferay-commerce/commit/4739238e7b109990f023f26f3c290f6724167afd.

**Pull request merged**
