### PR TITLE
Commerce 1738

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
ci:test

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test
Happy first PR! 🎉 
CI commands have to be in their own comments (i.e. not in the initial-comment/description of a PR), just FYI. Also, they'll only work if you've added yourself to the Liferay organization (see [here](https://grow.liferay.com/share/Pull+Request+Tester+for+Liferay+Developers) for more details if you still need to do this).

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
@andrea-ale-sbarra if you run `./gradlew formatSource`, it should automatically fix these issues. (There are a few source formatting issues that are caught in CI that don't get caught locally... I'm still not sure why. But if that happens, you'll need to try to fix manually. Let me know if you have problems with this.)

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Pull request closed without merging**
