### PR TITLE
COMMERCE-600 deprecated some methods moved to CommerceSubscriptionEngine

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
@marco-leo @ethanbustad  please check this PR

**Comment by ethanbustad** [comment]
ci:test
@luca-pellizzon @yichenroy looks like a CI error

**Comment by yichenroy** [comment]
@ethanbustad 
Looks like there was a network issue during an rsync operation, the re-test should be okay.

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
@marco-leo
this one can be checked and then merged

**Pull request merged**
