### PR TITLE
COMMERCE-455 Added multi delete on notification templates

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
Failure should be fixed by https://github.com/liferay/com-liferay-commerce/pull/137.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
Fixed SF issue and resent here: https://github.com/liferay/com-liferay-commerce/pull/138.

**Pull request closed without merging**
