### PR TITLE
COMMERCE-1310 Catalog schema

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-1310

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
@ethanbustad do we want to merge those on next branch?

**Comment by ethanbustad** [comment]
@marco-leo it's up to you. We could keep all of this code in a feature branch until it's all done, or merge what we can into 7.1.x-next (until we start writing code that would break other things...). I don't really have a preference.

Edit: The progress we've made so far is merged together at https://github.com/ethanbustad/com-liferay-commerce/commits/multi-site-catalog if you want to check it out.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
Closing, sent to https://github.com/liferay/com-liferay-commerce/pull/825.

**Pull request closed without merging**
