### PR TITLE
LRQA-43110 Fix test.properties updates

### PR DESCRIPTION
**Pull request by iovaneale**

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:retest

**Comment by yichenroy** [comment]
ci:test

**Comment by jpince** [comment]
ci:stop

**Comment by iovaneale** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test

**Comment by ethanbustad** [comment]
@iovaneale I think this is finally an accurate test result :)

**Comment by iovaneale** [comment]
Yes @ethanbustad , it definitely is! I'll take a look at the failures in a while, thanks for the effort to everyone!

/cc @jpince @marco-leo @yichenroy  @brianwulbern

**Comment by iovaneale** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:stop

**Comment by iovaneale** [comment]
Sent to #148

**Pull request closed without merging**
