### PR TITLE
COMMERCE-583 fix commerce-test test

### PR DESCRIPTION
**Pull request by luca-pellizzon**
@marco-leo @ethanbustad please review

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
Just forgot about formatSource 😋 
Now should be ok @marco-leo

**Comment by luca-pellizzon** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by marco-leo** [comment]
ci:retest

**Comment by ethanbustad** [comment]
ci:retest

**Comment by luca-pellizzon** [comment]
ci:test

**Pull request merged**
