### PR TITLE
COMMERCE-686 Search component

### PR DESCRIPTION
**Pull request by marco-leo**
@gcmznt Please see my changes

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
@ethanbustad Please help me with the ci error

**Comment by ethanbustad** [comment]
@marco-leo looks like this is a problem in portal 7.1.x -- I'll see if it's been fixed yet.

**Comment by ethanbustad** [comment]
@jpince can you take a look? I don't see a fix for this anywhere yet.

**Comment by jpince** [comment]
@ethanbustad fix is in Brian's queue https://github.com/brianchandotcom/liferay-portal-ee/pull/22846

**Comment by ethanbustad** [comment]
Thanks, @jpince!

**Pull request merged**
