### PR TITLE
Fix some imports for 7.2 compat 

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
Error caused by [COMMERCE-2283](https://issues.liferay.com/browse/COMMERCE-2283). Working on a fix.

**Comment by ethanbustad** [comment]
ci:test
Fix merged in private repo -- we'll see whether it'll apply yet or not.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@marco-leo merging this to fix 7.2 compatibility, and to keep the demo team moving.

**Pull request merged**
