### PR TITLE
COMMERCE-1133 Fix scss file names (as per BChan) (2)

### PR DESCRIPTION
**Pull request by ethanbustad**
Resent from https://github.com/liferay/com-liferay-commerce/pull/676.

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
forgot to push latest fixes to private repo :/

**Comment by ethanbustad** [comment]
ci:test
rebased on latest 7.1.x-next branch (post-1.1.4)

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@marco-leo please merge!

**Comment by ethanbustad** [comment]
@marco-leo we really need to merge this; it was a direct request from BChan. Please talk to me if you have concerns. He wanted it in before we release again.

**Comment by ethanbustad** [comment]
@marco-leo @gcmznt @FabioDiegoMastrorilli  @gianmarcobrunialti any progress on this? Haven't seen any of these changes go in so far

**Comment by marco-leo** [comment]
@gianmarcobrunialti can you apply this to Speedwell and Minium?

**Pull request closed without merging**
