### PR TITLE
COMMERCE-2261 fixed commerce product test classes

### PR DESCRIPTION
**Pull request by riccardo-alberti**
To be merged after #1595

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by riccardo-alberti** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by riccardo-alberti** [comment]
ci:test

**Comment by riccardo-alberti** [comment]
ci:test

**Pull request closed without merging**
