### PR TITLE
COMMERCE-2351 Fixed category friendly url update

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
tests should be fixed in upstream now

**Comment by alecsloan** [comment]
see #1598

**Review by ethanbustad — APPROVED** [review]

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/1598

**Pull request closed without merging**
