### PR TITLE
COMMERCE-600 new subscription management

### PR DESCRIPTION
**Pull request by luca-pellizzon**
@marco-leo do NOT merge yet plese.
The subscription actions confirmation is still missing.

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by ethanbustad** [comment]
@luca-pellizzon you'll need to rerun baseline now that you're on top of 1.1.1 -- we'll need a major version increment again.

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by ethanbustad** [comment]
@luca-pellizzon since other PRs are passing, this failure must be introduced by your commits -- `compileTestIntegrationJava` fails for the `commerce-product-type-virtual-order-test` module.

Looking at the console, `CommerceVirtualOrderItemLocalServiceTest.java` is trying to import `CommerceSubscriptionCycleEntry` and `CommerceSubscriptionCycleEntryLocalService`, which I think you just removed. So we'll probably need to fix those tests :/

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Pull request merged**
