### PR TITLE
COMMERCE-617 Fixed missing labels

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:retest

**Comment by marco-leo** [comment]
@ethanbustad Please help with this

**Comment by ethanbustad** [comment]
1) `paypal=PayPal` is already a portal language key, so this duplicate isn't needed.

I'll have to look into the second one a bit more

**Comment by ethanbustad** [comment]
Alright, simple fix:
1) Remove `paypal=Paypal`
2) Remove `detail=Detail`
Both are already in portal. (Not sure why that second error is so much less readable than the first one...!)

**Comment by alessiorendina** [comment]
ci:retest

**Comment by alessiorendina** [comment]
@ethanbustad Thank you!

**Comment by alessiorendina** [comment]
@ethanbustad it fails again, is it the same error?

**Comment by ethanbustad** [comment]
There were 2 more duplicate keys. I removed them and sent it to https://github.com/liferay/com-liferay-commerce/pull/119.

Running source formatter locally doesn't find these errors, unfortunately -- I think the code has to be embedded in portal for the duplicate lang key logic to run. But you can check for duplicates yourself with:

    grep -F -f - /path/to/liferay-portal/portal-impl/src/content/Language.properties < ./commerce-lang/src/main/resources/content/Language.properties

**Pull request closed without merging**
