### PR TITLE
Commerce 1168 Refactor cleanUserSegmentsChache -> cleanUserSegmentsCache

### PR DESCRIPTION
**Pull request by alecsloan**
Let me know if you have any questions.

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/713

**Pull request closed without merging**
