### PR TITLE
Emp 96

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by iovaneale** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
@iovaneale @ethanbustad the failure was actually accurate as the code introduced a js error, I am retesting after push the fix. @iovaneale This means your tests are working :)

**Pull request merged**
