### PR TITLE
COMMERCE-2012 fe components moved into the right modules

### PR DESCRIPTION
**Pull request by fabio-d-m**
- tables
- sidepanels
- modals
- step trackers

@marco-leo @ethanbustad this replaces https://github.com/liferay/com-liferay-commerce/pull/1517

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by fabio-d-m** [comment]
ci:test

**Comment by fabio-d-m** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/1533

**Pull request closed without merging**
