### PR TITLE
COMMERCE-1240 | 7.1.x-next

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
[Commerce API Scrum board](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=3928)
----
Ticket: https://issues.liferay.com/browse/COMMERCE-1240

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
@ZoltanTakacs Do we need this just for commerce? Are we sure is not already done by Vulcan, should DXP headless module need this too?  // @brianchandotcom @Nhpatt

**Comment by marco-leo** [comment]
@ZoltanTakacs just confirmed with @nhpatt. let's send this to vulcan.  Thanks . //cc @brianchandotcom

**Comment by ZoltanTakacs** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/70927

**Pull request closed without merging**
