### PR TITLE
COMMERCE-1362 Since we need assetLinkEntryIds lets use those instead of assetLinkIds for updating links

### PR DESCRIPTION
**Pull request by alecsloan**
Let me know if you have any questions

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
Errors should now be fixed by https://github.com/liferay/com-liferay-commerce/pull/831, but new ones are present until https://github.com/liferay/com-liferay-commerce/pull/838 and https://github.com/liferay/com-liferay-commerce/pull/841 are merged. Will retest once those are in.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:test
didn't update the private repo with the latest fixes :(

**Pull request merged**
