### PR TITLE
COMMERCE API - 2018 FEB 19

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
[Commerce API Scrum board](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=3928)
----
Tickets: 
- https://issues.liferay.com/browse/COMMERCE-941
- https://issues.liferay.com/browse/COMMERCE-961
- https://issues.liferay.com/browse/COMMERCE-1025
- https://issues.liferay.com/browse/COMMERCE-1003

/cc @igorbeslic @ivicac @matijapetanjek @Commando18

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:retest

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by ZoltanTakacs** [comment]
ci:test

**Pull request merged**
