### PR TITLE
COMMERCE-2050

### PR DESCRIPTION
**Pull request by petershin**
@pyoo47 @hhuijser

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by ethanbustad** [comment]
Awesome, thanks, @petershin! I'll work on fixing the validation failures.

**Comment by ethanbustad** [comment]
Fixed and sent along to https://github.com/liferay/com-liferay-commerce/pull/1592. Thanks again, @petershin!

**Comment by marco-leo** [comment]
@fabio please see PEter and Ethan changes

**Pull request closed without merging**
