### PR TITLE
COMMERCE-1368

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by marco-leo** [comment]
@Commando18 please rebase this pull

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
@Commando18 I think we need to use project dependencies for `commerce-price-list-api` after this major change -- that's probably the cause of this failure.

**Review by ethanbustad — APPROVED** [review]

**Comment by ethanbustad** [comment]
rebased and sent to https://github.com/liferay/com-liferay-commerce/pull/1786.

**Pull request closed without merging**
