### PR TITLE
COMMERCE-1287 Prevent XSS on some sku outputs

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
SF issue fixed in a separate pull

**Comment by ethanbustad** [comment]
ci:test
forgot to push fixes to private :(

**Comment by ethanbustad** [comment]
ci:test
my bad, _still_ hadn't updated private 🤦‍♂

**Pull request merged**
