### PR TITLE
Update Source Formatter

### PR DESCRIPTION
**Pull request by ethanbustad**
This'll be good to merge before we move into the central repo.

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
file is there.... retry

**Comment by ethanbustad** [comment]
ci:test
ugh, trying one more time before pinging IT

**Comment by marco-leo** [comment]
@ethanbustad is this pull still valid?

**Comment by ethanbustad** [comment]
Yes, but it's not urgent. We'll just want to merge it in before killing the subrepo. I'll rebase it in the next couple days.

**Comment by marco-leo** [comment]
ok, closing for now

**Pull request closed without merging**
