### PR TITLE
COMMERCE-1086 - Mercanet and more

### PR DESCRIPTION
**Pull request by luca-pellizzon**
@marco-leo

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:help

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
updated 7.1.x-next in private

**Comment by ethanbustad** [comment]
Rebased and sent to https://github.com/liferay/com-liferay-commerce/pull/633.

**Pull request closed without merging**
