### PR TITLE
COMMERCE-992 Add backUrl handling after editing account user

### PR DESCRIPTION
**Pull request by alecsloan**
Let me know if you have any questions.

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — CHANGES_REQUESTED** [review]
Talked about a couple changes.

**Comment by alecsloan** [comment]
@ethanbustad force-push reflects discussed changes

**Review by ethanbustad — APPROVED** [review]

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Pull request merged**
