### PR TITLE
COMMERCE-2356 commerce-lang Missing language keys in the Control Panel

### PR DESCRIPTION
**Pull request by riccardo-ferrari**

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:start

**Comment by riccardo-ferrari** [comment]
ci:test

**Comment by ethanbustad** [comment]
@riccardo-ferrari can you also include a build-lang commit?

**Review by ethanbustad — APPROVED** [review]

**Comment by riccardo-ferrari** [comment]
> @riccardo-ferrari can you also include a build-lang commit?

i'm on it

**Comment by riccardo-ferrari** [comment]
added buildLang commit

**Pull request merged**
