### PR TITLE
Commerce 2255

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
Hi @marco-leo , I've just applied the change that @ethanbustad requested on the previous PR.
Please, let me know if is fine to use this branch or do I need to open a new issue on JIRA and then rework the commit messages

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
tests should be fixed in upstream now

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
I'm closing this because it's just to old to be merged.

**Pull request closed without merging**
