### PR TITLE
COMMERCE-1791 Fixed account upsert

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:retest

**Comment by marco-leo** [comment]
@ethanbustad this looks a CI fail

**Comment by ethanbustad** [comment]
@marco-leo looking at this again, I think they must've updated source formatter, and now we really do need to update to 1.0.19. But that's an issue in upstream, not this PR, so no need to fix here. I'll send a fix.

**Pull request merged**
