### PR TITLE
COMMERCE-1183 Catalog Rule Application Type configuration

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-1183

### CODE REVIEW

**Comment by ethanbustad** [comment]
@marco-leo I believe this works like you wanted. Feel free to change as you see fit.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/720

**Pull request closed without merging**
