### PR TITLE
COMMERCE-697 | COMMERCE-622

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:help

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
^ looks like these failures are in upstream. Will send a fix.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
updated private repo to match new hash we just pushed

**Comment by marco-leo** [comment]
Error looks not related

**Comment by ethanbustad** [comment]
@marco-leo yeah I think it's a functional test failure. Test is looking for text "All products", but I think it should be looking for "All Products". @iovaneale 

More info at https://testray.liferay.com/reports/production/logs/test-1-14/1544466834731/test-subrepository-acceptance-pullrequest(7.1.x)/28/subrepository-functional-tomcat90-mysql57-jdk8/5/0/LocalFile.CommerceAdmin_CreateNewCatalogRule/summary.html.gz.

**Comment by marco-leo** [comment]
@ethanbustad yeap! that is a good news.

**Comment by iovaneale** [comment]
You are right, @ethanbustad, it looks for "All products". Probably the label has been recently updated since locally I see it w/o capital "p" (attached screenshot). Anyways I'll push the change soon. Thanks.
screenshot from 2018-12-11 10-27-59

**Comment by ethanbustad** [comment]
@iovaneale interesting, I think it should be "All Products", with a capital P. I wonder how/why it got changed.....

Edit: Looking at the code, I think it is "All Products" now.... but then why is it showing up with a lower-cased "p" on your local and in CI...?

**Comment by iovaneale** [comment]
@ethanbustad Btw, also the lpkg I am testing has the lower-cased "p".

**Pull request merged**
