### PR TITLE
Fix new SF issues

### PR DESCRIPTION
**Pull request by ethanbustad**

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
@ethanbustad I will merge this pull, but please take a look to those failures

**Comment by ethanbustad** [comment]
@marco-leo created https://issues.liferay.com/browse/COMMERCE-1294 to look into it. Thanks!

**Pull request merged**
