### PR TITLE
Commerce 1748  Add method to get OrderItemsCount by cpInstanceId

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by justmerge** [comment]
Hey Alec! Great, thanks I've understood how we generalized the method in order to have it available at the level of the service of the `CommerceOrder`. 👍

**Comment by gianmarcobrunialti** [comment]
Hey Alec! Great, thanks I've understood how we generalized the method in order to have it available at the level of the service of the CommerceOrder. 👍Maybe it would be nice to use this also from the AddToCartButton in the Catalog, since there too we're deriving the order items count indirectly. Am I wrong?

**Comment by alecsloan** [comment]
@gianmarcobrunialti ~yes good point, I wasn't aware of that. I'll change that instance too!~ Wait scratch that, this changes that case already. If you're thinking of a different file plz point me to it, thanks!

**Comment by alecsloan** [comment]
Force push reflects rebase

**Pull request merged**
