### PR TITLE
COMMERCE-698 Use portal release jar dependency

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-698

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@yichenroy @jpince have you guys seen errors like this before? I've never seen these tests fail, and the error messages don't help much :(

**Comment by yichenroy** [comment]
@ethanbustad 
I have not seen this particular error before, but it looks like all the failures are files having trouble finding the reference to `com.liferay.portal.kernel.util.ParamUtil`, does this error happen on any other pull? 
It may be something that was changed in the dependencies in this pull.

**Comment by ethanbustad** [comment]
Alright, thanks, @yichenroy. I haven't seen it on any other PRs, so it must be caused by the dependency changes here somehow....

**Comment by ethanbustad** [comment]
@yichenroy oh yeah, nvm, these are actually our unit tests! Didn't realize :)

**Comment by yichenroy** [comment]
@ethanbustad cool, hopefully it is easy to resolve.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Pull request closed without merging**
