### PR TITLE
COMMERCE-704 Here's hoping....

### PR DESCRIPTION
**Pull request by ethanbustad**

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test:2b16825f9995a60d5d8e22c77c3c0bb2ac0e0936

**Comment by ethanbustad** [comment]
looks like these failures are in upstream :/ -- https://github.com/ethanbustad/com-liferay-commerce/pull/25

**Comment by ethanbustad** [comment]
ci:test:4982154f8b5acca2cd4f63559684cebdb82c9931

**Comment by ethanbustad** [comment]
@yichenroy @pyoo47 this seems to be a new error, but happens against old code, too. [Just tested this PR](https://github.com/liferay/com-liferay-commerce/pull/336#issuecomment-450209334) against an upstream sha that passed [elsewhere](https://github.com/liferay/com-liferay-commerce/pull/327), but now tests fail. But the failure isn't coming from this PR's changes, because [the failure is also happening](https://github.com/ethanbustad/com-liferay-commerce/pull/25#issuecomment-450206829) on `7.1.x-next` upstream.... Can you guys take a look?

**Comment by pyoo47** [comment]
@ethanbustad Most likely this is because of a bug introduced yesterday when I merged a new change from Roy. He spotted some problems with his changes this morning and has been working on a fix.

**Comment by yichenroy** [comment]
@ethanbustad 
This looks like an actual failure unrelated to CI that happens when tested against the latest liferay-portal-7.1.x bundles available, reproduced at sha `8a12b3317b04bad3371e41fab22dc5b8d5b27977` from the [clean PR you ran](https://github.com/ethanbustad/com-liferay-commerce/pull/25#issuecomment-450206829).

[The passing PR ](https://github.com/liferay/com-liferay-commerce/pull/327) uses the same 7.1.x-next base sha `4982154f8b5acca2cd4f63559684cebdb82c9931` from the Commerce subrepository, but it was tested against the latest liferay-portal-7.1.x at that time (the console links expired in the pullrequest so I am unable to see which portal sha it was running against, but it must have been a sha for a bundle that was built at least 9 days ago). 

cc @pyoo47

**Comment by ethanbustad** [comment]
Oh, ok. Thanks, guys! @pyoo47 @yichenroy

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
hopefully the portal problem is gone now?

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
Resent to https://github.com/liferay/com-liferay-commerce/pull/344, rebased on latest 7.1.x-next.

**Pull request closed without merging**
