### PR TITLE
COMMERCE-1453 remove source formatter suppressions fort product-definitions-web and product-service

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by marco-leo** [comment]
@alecsloan   can you please to rebase this

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/1497

**Pull request closed without merging**
