### PR TITLE
COMMERCE-874 Fix commerce-cart-taglib deploy issue (7.1.x-next)

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-874

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@jpince @yichenroy do either of you know what's going on here? The results page looks like it's frozen or something.... and I would've expected validation results by now.

Same weirdness in these 2 PRs: https://github.com/liferay/com-liferay-commerce/pull/491, https://github.com/liferay/com-liferay-commerce/pull/494

**Comment by yichenroy** [comment]
@ethanbustad 
The load is quite high right now (currently 2000 jobs in queue), a job from this build is still in queue.

`[beanshell] 0 Starting  / 0 Missing  / 1 Queued  / 0 Running  / 0 Completed  / 1 Total `

**Comment by ethanbustad** [comment]
Got it.... thanks, @yichenroy.

**Comment by ethanbustad** [comment]
@marco-leo merging this in to fix CI issues.

**Pull request merged**
