### PR TITLE
Commerce 1453 bnd suppression fixes

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
@ethanbustad I'll reclaim responsibility of #1473

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by alecsloan** [comment]
ci:test

Not sure how to fix the compileJSPJava issue but the SF one should be fixed.

**Comment by pyoo47** [comment]
Sorry, I accidentally aborted the first run.. I initiated a new one to take it's place..

**Comment by pyoo47** [comment]
Also, I'm currently working with Peter Shin to fix the compileJSPJava issue.. hoping to have a fix sent to BChan tomorrow.

**Comment by alecsloan** [comment]
ahh ok, not something we need to worry about then? Thanks!

**Comment by pyoo47** [comment]
Yeah.. just to be specific, we are trying to fix the failure in `subrepository-unit-jdk8`

```
     [echo] * What went wrong:
     [echo] Failed to capture fingerprint of input files for task ':apps:commerce:commerce-order-web:generateJSPJava' property 'jspCClasspath' during up-to-date check.
     [echo] > Unable to find com.liferay.expando.taglib.jar in /opt/dev/projects/github/liferay-portal-7.1.x/bundles/osgi
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.UncheckedIOException: Failed to capture fingerprint of input files for task ':apps:commerce:commerce-order-web:generateJSPJava' property 'jspCClasspath' during up-to-date check.
     [echo] 	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.fingerprintTaskFiles(CacheBackedTaskHistoryRepository.java:360)
     [echo] 	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.createExecution(CacheBackedTaskHistoryRepository.java:163)
     [echo] 	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.access$100(CacheBackedTaskHistoryRepository.java:76)
     [echo] 	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository$1.getCurrentExecution(CacheBackedTaskHistoryRepository.java:123)
     [echo] 	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:200)
     [echo] 	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:94)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:50)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [echo] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [echo] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91) 
```

**Comment by pyoo47** [comment]
ci:test

**Comment by marco-leo** [comment]
@alecsloan won't merge this pull we need to send small pulls for each one, just were no logic is affected

**Comment by alecsloan** [comment]
@marco-leo which logic changes did you not like? I just went back through the diff and it look like only changes to constants

**Pull request closed without merging**
