### PR TITLE
COMMERCE-621 Product Subscriptions

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
@Commando18 unfortunately `gradlew baseline` fails on the first module it finds with the wrong version. I'm not sure how you usually run this, but when I'm doing baseline checks I always just keep running it till it succeeds, so I make sure to get all the necessary version increments.

**Comment by ethanbustad** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:retest

**Comment by alessiorendina** [comment]
ci:retest

**Comment by alessiorendina** [comment]
ci:retest

**Comment by marco-leo** [comment]
@Commando18 Tests are failing. Please fix

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@yichenroy do you know why this error is happening?

**Comment by yichenroy** [comment]
@ethanbustad 
The `7.1.x-next` branch needs to be sync'd from com-liferay-commerrce to com-liferay-commerce-private, commit with sha '115ea397e79c5c16cd2969738a7f3924b193c3c1' does not exist on `7.1.x-next` of com-liferay-commerce-private.

Actual failure message:
`[beanshell] java.lang.RuntimeException: Unable to create local branch 7.1.x-next at 115ea397e79c5c16cd2969738a7f3924b193c3c1
[beanshell] fatal: Not a valid branch point: '115ea397e79c5c16cd2969738a7f3924b193c3c1'.`

**Comment by ethanbustad** [comment]
_Sigh_ alright, I'll sync them. Thanks!

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
^ the semantic versioning issue is in upstream, but the integration test failure seems valid.

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:retest

**Comment by marco-leo** [comment]
ci:retest

**Comment by ethanbustad** [comment]
ci:test

**Comment by alessiorendina** [comment]
Forwarded to [#212](https://github.com/liferay/com-liferay-commerce/pull/212)

**Pull request closed without merging**
