### PR TITLE
Commerce 1648 Minium theme changes

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Review by ethanbustad — APPROVED** [review]

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
......

**Comment by ethanbustad** [comment]
^ @alecsloan this SF error is relevant to your PR (but the ModulesStructureTest error is not)

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
SF issue should be fixed by #1714

**Pull request merged**
