### PR TITLE
COMMERCE-1641 Speedwell B2C Commerce Theme

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by ethanbustad** [comment]
Looks like a lot of files are duplicated in an `out` directory -- is this necessary?

**Comment by ethanbustad** [comment]
GitHub's choking on the huge diff, so I can't make inline comments atm. I'll make a few comments here:
* Please run `gw formatXml` -- some xml files don't have attributes and such sorted properly, but this task should take care of it all. Run `gw formatSource` again afterward, because sometimes the tasks disagree :/. But everything that they agree on will be necessary improvements.
* There's a few cases in `SpeedwellSiteInitializer` where we create a new `HashMap` for a single localization key-value pair. I think this would be an appropriate place to use `Collections.singletonMap` instead.
* There's a bunch of `_log.info` statements in `SpeedwellSiteInitializer` where the capitalization isn't consistent. We should make these consistent
* The `.ftl` files have some indentation issues.... looks like they're mostly good, there's just several lines in most of the files that are off (often unindented completely for no apparent reason)
* There are some `.jpeg` files and some `.jpg` -- we should probably make this consistent
* All language property values should be capitalized. I'm guessing they're currently not so they match better with the desired look-and-feel, but lower-casing should be achieved using CSS if that's the case.
* `*.scss` filenames should be underscore delimited, rather than dash delimited or mixed case
* scss entries should be alphabetically sorted if there's no "cascade" reason for them to be sorted otherwise
* pretty sure scss files should be indented with tabs and that they shouldn't end in a newline

If this is too much to do before merging in, please prioritize removing the `out` directory (if not needed) and fixing the filenames (and feel free to do anything else that seems like low-hanging fruit). The other stuff can wait till after the first merge if need be.

**Review by ethanbustad — CHANGES_REQUESTED** [review]
Ugh, it requires a review comment. See my prior comment for what should be changed. We can have a call about these things on Monday, too, if that would be helpful!

**Comment by ethanbustad** [comment]
@marco-leo I assume this PR can be closed since you merged it in https://github.com/liferay/com-liferay-commerce/pull/1432?

**Comment by marco-leo** [comment]
@ethanbustad yeap, sorry forgot it

**Pull request closed without merging**
