### PR TITLE
7.2.x

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
@ethanbustad can you take care please?

**Comment by ethanbustad** [comment]
Yessir, will do.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
Resent to https://github.com/liferay/com-liferay-commerce/pull/1501.

**Pull request closed without merging**
