### PR TITLE
COMMERCE-1133 Fix scss file names (as per BChan)

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-1133

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
@ethanbustad  Giacomo is refactoring css during this week and next one, to add support to mobile and RTL, will merge this pull later to avoid conflicts in his side

**Comment by ethanbustad** [comment]
Closing - redid and resent to https://github.com/liferay/com-liferay-commerce/pull/774.

**Pull request closed without merging**
