### PR TITLE
COMMERCE-806-798-799-853-71x

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
For 7.1.x-next: https://github.com/liferay/com-liferay-commerce/pull/476

/cc @igorbeslic @ivicac @matijapetanjek

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
/cc @ethanbustad 
ci:test

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ethanbustad** [comment]
@ZoltanTakacs my bad, I'll consider this passing.

**Comment by ZoltanTakacs** [comment]
Thank you! :) 👍

**Comment by ethanbustad** [comment]
Merged.

**Pull request closed without merging**
