### PR TITLE
Apply SF change for Yaml files | 7.1.x-next

### PR DESCRIPTION
**Pull request by ZoltanTakacs**

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
Pretty sure this is now fixed by https://github.com/liferay/com-liferay-commerce/pull/631, so we probably can close this.

**Comment by ZoltanTakacs** [comment]
Closing this PR based on the comment above.

**Pull request closed without merging**
