### PR TITLE
COMMERCE-619 product subscriptions

### PR DESCRIPTION
**Pull request by luca-pellizzon**
@marco-leo please review

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:retest

**Comment by marco-leo** [comment]
@luca-pellizzon you have to rub gradelw baseline

**Comment by luca-pellizzon** [comment]
ci:retest

**Comment by luca-pellizzon** [comment]
ci:retest

**Pull request closed without merging**
