### PR TITLE
COMMERCE-552 Allow user to choose AND or OR search

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-552

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
@ethanbustad can you please add an integration test for this?

Thanks

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/117

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/117

**Pull request closed without merging**
