### PR TITLE
LRQA-42506 | 7.1.x

### PR DESCRIPTION
**Pull request by iovaneale**
https://issues.liferay.com/browse/LRQA-42506

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:retest

**Comment by marco-leo** [comment]
ci:retest

**Comment by iovaneale** [comment]
@Ithildir What do you think this error belongs to?

**Comment by Ithildir** [comment]
@iovaneale, not sure, it seems like a CI problem...

**Comment by Ithildir** [comment]
ci:retest

**Comment by ethanbustad** [comment]
I know the jenkins servers lost some network mounts yesterday - I thought they fixed everything, but this looks like it could be related...

**Comment by marco-leo** [comment]
@jpince help please

**Comment by jpince** [comment]
@michaelhashimoto @yichenroy @kenjiheigel can you please look at this? I think this is where it failed:
```
prepare-portal-repository:
     [exec] Warning: Permanently added 'test-1-0,172.16.0.50' (RSA) to the list of known hosts.
     [exec] Warning: Permanently added 'test-1-0,172.16.0.50' (RSA) to the list of known hosts.
     [exec] rsync: read errors mapping "/opt/java/jenkins/userContent/bundles/test-portal-acceptance-upstream(7.1.x)/244/git-hash": No such device or address (6)
     [exec] WARNING: git-hash failed verification -- update discarded (will try again).
```
7.1.x & 7.1.x-private git hashes look fine, 7.1.x pulls to Brian are also fine. Thanks!

Commerce team, feel free to reach out directly to QA Engineering in the future if you see an issue you believe to be related to CI Infrastructure.

**Comment by yichenroy** [comment]
@jpince @iovaneale @marco-leo
Hello, the failure came from a CI issue (missing a pre-built bundle used for subrepository pullrequests on 7.1.x branch) that should now be resolved by the following ticket:
https://issues.liferay.com/browse/LRQA-41902

Please try to retest again after Aug 2, 2018 - 10 pm PDT so a bundle will be available from upstream.

**Comment by iovaneale** [comment]
ci:retest

**Comment by iovaneale** [comment]
Hi @yichenroy, retesting went unsuccessful. SF asks for dependencies that Commerce test modules already have, so I suppose it's an SF malfunctioning.

``BUILD FAILED
     [echo] 
     [echo] Total time: 41.519 secs
     [echo] Gradle build finished at 2018-08-03 08:52:07.908.
     [echo] POM relocation to an other version number is not fully supported in Gradle : xml-apis:xml-apis:2.0.2 relocated to xml-apis:xml-apis:1.0.b2.
     [echo] Exception in thread "main" java.lang.Exception: Found 27 formatting issues:
     [echo] 1: Use a project dependency instead of a module dependency: ./commerce-price-list-test/build.gradle 9 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 2: Use a project dependency instead of a module dependency: ./commerce-price-list-test/build.gradle 10 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 3: Use a project dependency instead of a module dependency: ./commerce-product-service/build.gradle 37 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 4: Use a project dependency instead of a module dependency: ./commerce-product-test/build.gradle 9 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 5: Use a project dependency instead of a module dependency: ./commerce-product-test/build.gradle 10 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 6: Use a project dependency instead of a module dependency: ./commerce-product-type-virtual-test/build.gradle 3 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 7: Use a project dependency instead of a module dependency: ./commerce-product-type-virtual-test/build.gradle 4 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 8: Use a project dependency instead of a module dependency: ./commerce-product-type-virtual-test/build.gradle 5 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 9: Use a project dependency instead of a module dependency: ./commerce-test/build.gradle 9 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 10: Use a project dependency instead of a module dependency: ./commerce-test/build.gradle 10 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 11: Use a project dependency instead of a module dependency: ./commerce-test/build.gradle 11 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 12: Use a project dependency instead of a module dependency: ./commerce-user-segment-test/build.gradle 9 (SourceCheck:GradleTestDependencyVersionCheck)``



/cc @jpince @marco-leo

**Comment by jpince** [comment]
@petershin can you please tell us if the changes asked for in build.gradle are correct? They seem consistent, but just want to make sure.

**Comment by jpince** [comment]
@iovaneale all SF questions should go to @petershin. Please only contact QA Engineering if the issue is infrastructure-related (test batch fails before it even gets to the test, or test fails for some reason that can't be explained by commerce code)

Also, please read the SF log carefully, as you can easily miss real errors. Even without Peter's answer, I am sure that Error 27 is real:
`27: ./commerce-support-web/src/main/resources/META-INF/resources/view.jsp`
Extra tab in these lines (and affecting the lines following):
https://github.com/liferay/com-liferay-commerce/blob/7.1.x/commerce-support-web/src/main/resources/META-INF/resources/view.jsp#L43
https://github.com/liferay/com-liferay-commerce/blob/7.1.x/commerce-support-web/src/main/resources/META-INF/resources/view.jsp#L120
https://github.com/liferay/com-liferay-commerce/blob/7.1.x/commerce-support-web/src/main/resources/META-INF/resources/view.jsp#L162
For a case like this where the output is very long, if I don't want to run source formatter locally, I usually have to copy-paste the entire log output into a text editor, and look at the two parts (`expected:` and `but was:`) side-by-side and line-by-line to detect the differences.

cc/ @marco-leo

**Comment by iovaneale** [comment]
@jpince Thanks. We were actually aware of the error 27, but not sure about gradle's ones.

/cc @marco-leo

**Comment by iovaneale** [comment]
ci:retest

**Comment by petershin** [comment]
@jpince - Sent a patch: https://github.com/brianchandotcom/liferay-portal-ee/pull/21266

**Comment by jpince** [comment]
@petershin so it's a temp suppression... so are the changes needed, or not?

**Comment by petershin** [comment]
@jpince - The change isn't needed.  The SF logic for suppressing subrepo suppressions will be updated at some point in the future and that section will likely be removed.

**Comment by jpince** [comment]
@iovaneale you'll need to wait until Peter's patch is merged into central, then SF should pass.

**Comment by petershin** [comment]
A faster workaround is to add the SF suppressions into the file below and then to rerun the CI tests:

https://github.com/liferay/com-liferay-commerce/blob/7.1.x/source-formatter-suppressions.xml

**Review by ethanbustad — APPROVED** [review]

**Comment by ethanbustad** [comment]
ci:retest

**Comment by marco-leo** [comment]
@jpince can you help us on fixing this  pull?

**Comment by jpince** [comment]
ci:test

**Pull request merged**
