### PR TITLE
Commerce 1453 Remove some product API suppressions

### PR DESCRIPTION
**Pull request by alecsloan**
CPDataSource.java
CPCompareUtil.java
CPContentContributor.java
VirtualCPTypeHelper.java

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
Try project dependencies here, too.

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
@alecsloan `Execution failed for task ':apps:commerce:commerce-product-content-web:compileJSP'.`

**Comment by alecsloan** [comment]
ci;test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
Poshi report shows the price is missing. I just tested with the simple renderer and I was able to see the price. Retesting just to double check.

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by marco-leo** [comment]
Can't remove those suppression, evaluate to rename the calsses with HTTP

**Pull request closed without merging**
