### PR TITLE
Lps 91420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by marco-leo** [comment]
Thanks @hhuijser

**Comment by marco-leo** [comment]
@ethanbustad I dodn't realized this pull was in 7.1.x.  Do you think is easier reverting it ?

**Comment by hhuijser** [comment]
@ethanbustad @marco-leo, for future reference, which branch am I supposed to send to?

**Comment by marco-leo** [comment]
@hhuijser 7.1.x-next

**Pull request merged**
