### PR TITLE
COMMERCE-1184 Only update the payment key if it doesn't match the existing one

### PR DESCRIPTION
**Pull request by alecsloan**
Let me know if you have any questions.

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by yichenroy** [comment]
`[exec] rsync: read errors mapping "/opt/java/jenkins/userContent/bundles/test-portal-acceptance-upstream(7.1.x)/747/git-hash": No such device or address (6)`

There are issues with the hardware that IT is looking into, please try retesting in a little while.

**Comment by ethanbustad** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — CHANGES_REQUESTED** [review]
use `(java.util.)Objects.equals` rather than a `!=`.

**Review by ethanbustad — APPROVED** [review]

**Pull request merged**
