### PR TITLE
Data integration management module

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
Continue the work that Guy left at https://github.com/liferay/com-liferay-commerce/pull/219

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
Resent on https://github.com/liferay/com-liferay-commerce/pull/274

**Comment by hhuijser** [comment]
@ZoltanTakacs is this inifinite loop still an issue? I ran SF on this branch without problems

**Comment by ZoltanTakacs** [comment]
Hey @hhuijser After manually sorting the imports, the problem's gone. Not sure what's fixed it 🤷‍♂️, but it's no longer reproducible. Thanks for the follow-up anyways! :)

**Comment by hhuijser** [comment]
@ZoltanTakacs would you be able to produce something (before the manual sorting) that would result in the loop?

**Comment by ZoltanTakacs** [comment]
@hhuijser I could reproduce this issue, please see this branch on the following PR: https://github.com/ZoltanTakacs/com-liferay-commerce/pull/3#issuecomment-451092057

**Pull request closed without merging**
