### PR TITLE
COMMERCE-686 Added add to cart api

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
Hey @Commando18, this PR conflicts with https://github.com/liferay/com-liferay-commerce/pull/308 and I can't figure out how to resolve them -- it seems like the 2 PRs are going in completely different directions with `CommerceCartApplication.java`. Can you take a look and resolve the rebase?

**Comment by alessiorendina** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:test

**Pull request closed without merging**
