### PR TITLE
COMMERCE-778 Fix failing test (7.1.x-next)

### PR DESCRIPTION
**Pull request by ethanbustad**

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
@yichenroy still some flakiness in the webhook? Tests didn't kick off on this PR, but did on https://github.com/liferay/com-liferay-commerce/pull/499, which I ran almost simultaneously.

**Comment by yichenroy** [comment]
@ethanbustad 
I don't see any abnormal activity from the webhook log, but I also don't see any request from this pullrequest, maybe the webhook never received any data.

We'll keep an eye out, let us know if it happens again.

**Comment by ethanbustad** [comment]
Alright, thanks, @yichenroy :)

**Comment by ethanbustad** [comment]
@marco-leo can we merge this in?

**Pull request merged**
