### PR TITLE
COMMERCE-873 Fix split-package issue (7.1.x-next)

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-873

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
Just to be sure this wasn't a Friday issue.
@pyoo47 @yichenroy any idea what this failure means?

**Comment by yichenroy** [comment]
@ethanbustad 
Not sure what this error is, but it is coming from a gradle task when it's trying to build a jar.
`org.gradle.api.UncheckedIOException: Failed to capture fingerprint of input files for task ':apps:commerce:commerce-api:jar' property 'rootSpec$2$1' during up-to-date check.`

Does this happen anywhere else?

**Comment by ethanbustad** [comment]
@yichenroy I think I've only seen it on this PR and its twin: https://github.com/liferay/com-liferay-commerce/pull/492 (codebase is virtually identical atm).

Maybe I'll see if Peter Shin has any ideas....

**Comment by petershin** [comment]
@ethanbustad - The `packageinfo` was removed and the `Exported-Package` instruction wasn't updated

Removing [commerce-api/bnd.bnd#L5](https://github.com/liferay/com-liferay-commerce/blob/7.1.x/commerce-api/bnd.bnd#L5) should fix it.

**Comment by ethanbustad** [comment]
Got it. Thanks, @petershin!

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@marco-leo merging this in to fix CI issues.

**Pull request merged**
