### PR TITLE
COMMERCE-1224 keep "active order" updated

### PR DESCRIPTION
**Pull request by luca-pellizzon**
@marco-leo

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by iovaneale** [comment]
@luca-pellizzon @marco-leo, after merging #747 we can retest this pull.

**Comment by iovaneale** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:test

**Pull request merged**
