### PR TITLE
COMMERCE-569 Allow order workflow only for b2b contexts

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
Failure should be fixed by https://github.com/liferay/com-liferay-commerce/pull/137.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Pull request merged**
