### PR TITLE
COMMERCE-1632 :)

### PR DESCRIPTION
**Pull request by igorbeslic**
Hi Liferay please review... thank you liferay!!

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
SF was fixed in another PR

**Comment by ethanbustad** [comment]
@igorbeslic looks like the failure is specific to this PR

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/1200

**Pull request closed without merging**
