### PR TITLE
COMMERCE-1453 Fix VariableDeclarationAsUsedCheck and remove suppression

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
@ethanbustad @alecsloan This pull is fine, let's rebase and make tests pass again

**Comment by alecsloan** [comment]
@marco-leo Rebased

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Pull request merged**
