### PR TITLE
COMMERCE-699 Fixed guest order merge

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:6dd1f48da81721f07a49065855a9256711a7437c

**Comment by alessiorendina** [comment]
ci:test:d26aacd923882d29c47d696a57bf165ff36aa352

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
Updated private repo.

**Comment by ethanbustad** [comment]
@marco-leo the only failing test here is the bad functional test, so I think we can treat this PR as "passing".

**Comment by marco-leo** [comment]
@ethanbustad agree

**Pull request merged**
