### PR TITLE
COMMERCE-643 Stick to a stable portal version for CI tests

### PR DESCRIPTION
**Pull request by ethanbustad**

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
Hey @pyoo47, I think we're encountering the same issue that Minhchau mentioned here https://loop.liferay.com/web/guest/home/-/loop/feed/13976846.

Would it be possible to set `baseline.jar.report.level=off` in some `build.properties` (like Minhchau suggests) in cases like this where we're specifying an older portal version?

**Comment by pyoo47** [comment]
@lesliewong92 Did this happen to you in your testing?

**Comment by lesliewong92** [comment]
@pyoo47 My testing only went up to making sure that the portal repository reverted to the correct version. So I did not get to the point where I would encounter this issue.

**Comment by lesliewong92** [comment]
@ethanbustad I'll add logic to set the property and test it against this pull.

**Comment by ethanbustad** [comment]
thanks, @lesliewong92!

**Comment by lesliewong92** [comment]
@ethanbustad looks like the last set of changes was able to fix the issue. I'll send in a pull with these changes and let you know when they're merged.

**Comment by lesliewong92** [comment]
ci:test

**Comment by lesliewong92** [comment]
@ethanbustad The changes were merged in earlier today. I just re-ran the test for a final check, and everything seems to be working fine. Sorry for the delay, there were some SF resource issues we had to take care of yesterday.

**Comment by ethanbustad** [comment]
Thanks, @lesliewong92!

@marco-leo, this is a new feature that allows us to test against a specific portal version, so we can avoid SF changes and build failures caused by portal. If you want, you can merge this in to keep us testing against a recent stable version (I think it's the FP2 hash).

**Pull request closed without merging**
