### PR TITLE
COMMERCE-1835

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
Hi @ethanbustad, finally I had to redo the PR. Just created a new branch with the same code. I'm sorry for the wrong PR of yesterday. Hope this one is fine.

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by marco-leo** [comment]
@andrea-ale-sbarra until validations don't pass I can't review the pull

**Comment by andrea-ale-sbarra** [comment]
Hi @marco-leo I've just run the formatSource task on that module but nothing has changed on my side, how can I make this pass the validation?

**Comment by ethanbustad** [comment]
@andrea-ale-sbarra we have this problem sometimes, where `gw formatSource` differs between local and CI. I'm trying to figure out the cause, and if I can find it I'll fix it in a separate PR. So I think your PR is fine as-is -- I'll try to remember to retest it once the issue is fixed.

**Comment by ethanbustad** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]
Yep, this is perfect, @andrea-ale-sbarra. Thank you!

**Comment by marco-leo** [comment]
@andrea-ale-sbarra please rebase this

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
weird failure... let's try again and see if it persists

**Pull request merged**
