### PR TITLE
Commerce 1453 Fix application list bnd suppression

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — COMMENTED** [review]
Hey @alecsloan , can you remove my commit from this PR? It just introduces an SF issue :). Once that's done I'm good with this PR.

**Comment by alecsloan** [comment]
ci:stop

**Comment by alecsloan** [comment]
ci:test

**Comment by marco-leo** [comment]
@alecsloan need to be rebased

**Review by ethanbustad — APPROVED** [review]

**Comment by marco-leo** [comment]
@alecsloan @ethanbustad @brianchandotcom As we are moving in portal we can  kill this application-list module and add a commerce constants to the PanelCategoryKeys . in portal

**Pull request closed without merging**
