### PR TITLE
COMMERCE-1239 Make order item checkboxes usable for deleting rows

### PR DESCRIPTION
**Pull request by alecsloan**
Let me know if you have any questions.

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by marco-leo** [comment]
@alecsloan please rebase this

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by alecsloan** [comment]
ci:test

**Comment by pyoo47** [comment]
I'm running a test using this pull request.. Please ignore any test results that follow this comment.

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:stop

**Comment by alecsloan** [comment]
> I'm running a test using this pull request.. Please ignore any test results that follow this comment.

@marco-leo This PR's test succeeded. Please LMK if you have any issues with it

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by marco-leo** [comment]
@Commando18 Please make sure we have this in the new adminui

**Pull request merged**
