### PR TITLE
COMMERCE-1777 Translations

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
Refers to https://github.com/liferay/com-liferay-commerce/pull/1451

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]
@gianmarcobrunialti feel free to include the `buildLang` content in the same PR in the future, just in a separate commit. This works, too, it just introduces an unclear dependency between PRs.

**Comment by ethanbustad** [comment]
ci:test
Tests may pass now that https://github.com/liferay/com-liferay-commerce/pull/1436 is merged in.

**Comment by gianmarcobrunialti** [comment]
@ethanbustad Alright, I had understood in a completely separate PR.

**Comment by marco-leo** [comment]
@gianmarcobrunialti please send this fix in https://github.com/liferay/com-liferay-commerce/pull/1451 Thanks

**Pull request closed without merging**
