### PR TITLE
COMMERCE-0 Update portal kernel version

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
@Commando18 Fix conflicts, and please create issues. Avoid the use of a generic COMMERCE-0

**Pull request closed without merging**
