### PR TITLE
COMMERCE-1469 Remove exports from commerce-product-service

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-1469

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
fluky failure -- retest

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
I like this pull should be safe to merge in, let's rebase it

**Comment by ethanbustad** [comment]
@marco-leo rebased

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
@marco-leo rebased again :)

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@marco-leo I think this should pass now. I had to manually increase a version -- not sure why baseline didn't do it automatically.

**Pull request merged**
