### PR TITLE
COMMERCE-2261 fixed commerce virtual order item test classes

### PR DESCRIPTION
**Pull request by riccardo-alberti**
To be merged after #1603

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by riccardo-alberti** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by riccardo-alberti** [comment]
ci:test

**Comment by riccardo-alberti** [comment]
ci:test

**Comment by marco-leo** [comment]
@ethanbustad Merging this, please ask changes if needed

**Comment by ethanbustad** [comment]
@marco-leo did you merge this one? still open

**Pull request closed without merging**
