### PR TITLE
COMMERCE-API Add externalReferenceCode to CommerceOrder, CommerceOrderItem and CommerceOrderNote

### PR DESCRIPTION
**Pull request by rodrigoguedes**

### CODE REVIEW

**Comment by marco-leo** [comment]
@ethanbustad Do we need an update process for the schema changes?

**Comment by ethanbustad** [comment]
@marco-leo I'm not sure :/. The db upgrade best-practices seem to have changed in 7.1, and I haven't had to do one yet. I'll try to find out.

**Comment by ethanbustad** [comment]
@marco-leo if we're not expecting people to have to upgrade DBs with a lot of content in them (since Commerce is pretty new), we can probably just increment the build number in `service-ext.properties` and have Liferay auto-upgrade for us: https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-1/configuring-service-properties. (I think we'd then also have to increment the required schema version number in commerce-service's `bnd.bnd`.)

**Comment by marco-leo** [comment]
@ethanbustad The problem with this approach if in future we do need to upgrade DBs with a lot of content, at that point we need to create upgrade processes and will be more complex to add.

**Comment by ethanbustad** [comment]
@marco-leo yeah that's a good point. It'd be better to use a single method throughout the product, rather than prioritizing short-term simplicity (and then most likely regretting it later).

**Comment by marco-leo** [comment]
@ethanbustad Yes. I prefer it. So this means that this pull need an update process :)

**Comment by marco-leo** [comment]
@rodrigoguedes we do need an upgrade process for add the new columns

**Comment by rodrigoguedes** [comment]
@marco-leo waiting for review

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@rodrigoguedes can you send a `baseline` commit?

Edit: and a commit for `formatSource` compliance?

**Comment by rodrigoguedes** [comment]
@marco-leo @ethanbustad https://github.com/liferay/com-liferay-commerce/pull/75/commits/733ef64751c2cde6859a89a363e28267627c855c Is this right?

**Comment by ethanbustad** [comment]
@rodrigoguedes mmmm yeah, that probably is necessary.

But we also need to update the semantic versioning of the modules that've been modified in this PR -- you can just run `./gradlew baseline` to increment the versions automatically. I think the first time it'll fail, but it should also make the necessary edits, so if you run it a second time it should pass.

There are also problems that `./gradlew formatSource` points out (CI didn't get this far in the tests included above, but I ran it locally to check). Some of them will be fixed automatically, but I think there are also some that will require manual fixes. Feel free to let me know if you're not sure of the correct resolution for any specific errors.

**Comment by rodrigoguedes** [comment]
@ethanbustad, fixed!

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
Thanks, @rodrigoguedes! Those changes all look good. There's just a few more than source-formatter complains about now, that will have to be made manually. See the guidelines here: https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/chaining.markdown.

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/100

**Pull request closed without merging**
