### PR TITLE
COMMERCE-482 fix rounding mode 

### PR DESCRIPTION
**Pull request by luca-pellizzon**
when calculating product pricelist price with non primary currency

@marco-leo

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:stop

**Review by ethanbustad — APPROVED** [review]
Hey @luca-pellizzon, I wonder if the field resets done [here](https://github.com/luca-pellizzon/com-liferay-commerce/blob/848052cd149c8cdf9255dfe7ce711a24da1f6605/commerce-taglib/src/main/java/com/liferay/commerce/taglib/servlet/taglib/PriceTag.java#L90-L99) can't be improved at all -- as it is, I'm a little worried that in the future, if new fields get added to the class that are modified inside of `setProductInfo` or `setPriceInfo`, they won't get added to this reset list, and the bug you're fixing will recur.

I definitely don't have a great answer to _how_ it can be improved at this point, but I thought I'd mention it in case you have any ideas. My only thought is we could change the signature of `setProductInfo` and/or `setPriceInfo` to take arguments for the objects they need access to, and then we could achieve the reset by passing in `null` or something -- which would then consolidate setting the field values into a single location.

If you have any thoughts, sweet! Otherwise, this way that you've done it will be fine for now.

**Comment by luca-pellizzon** [comment]
Hi @ethanbustad pretty much everything can always be improved 😄 
That said, changing the signatures means also refactoring all classes using it. But I think that an intermediate approach could be a "reset" method that can be eventually extended by others.

**Comment by ethanbustad** [comment]
Haha, good point, @luca-pellizzon :smile: 

My concern is more like this... given the following information:
* `setPriceInfo` sets some fields -- looking at the implementation, I see that it sets `_formattedPromoPrice` and `_formattedPrice` (and `_commerceDiscountValue`, `_displayDiscountLevels`, and `_decimalFormat` via nested setters)
* `setProductInfo` also sets some fields -- `_quantity` and `_cpInstance`
* You can tell from the method names that some fields are being set, but it's not clear exactly _which_ fields are being set...
* When an exception is thrown in the `try` block, we need to reset (some of?) the global fields to prevent undefined behavior (precisely what this PR is intended to fix).

But... which fields need to be reset? Do all fields need to be reset, or just the fields modified by `setPriceInfo` and `setProductInfo`? Right now, how is [this list of fields I mentioned](https://github.com/luca-pellizzon/com-liferay-commerce/blob/848052cd149c8cdf9255dfe7ce711a24da1f6605/commerce-taglib/src/main/java/com/liferay/commerce/taglib/servlet/taglib/PriceTag.java#L90-L99) defined? Should it be the same list as [in `cleanUp`](https://github.com/luca-pellizzon/com-liferay-commerce/blob/848052cd149c8cdf9255dfe7ce711a24da1f6605/commerce-taglib/src/main/java/com/liferay/commerce/taglib/servlet/taglib/PriceTag.java#L157-L166)?

If we can make the intention of the `catch` block more clear, then I think we'll have a much easier time (and less chance of new bugs!) next time we have to modify the `PriceTag` class.

**Comment by marco-leo** [comment]
@ethanbustad @luca-pellizzon The intention of the catch method is: In case of error, we can't break the UI , we still have to show the product, but we don't display the price. 

@ethanbustad I will merge the pull, but if you want to refactor this, feel free to do.

**Pull request merged**
