### PR TITLE
COMMERCE-1246 Make Zip a required model field

### PR DESCRIPTION
**Pull request by alecsloan**
Let me know if you have any questions.

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by alecsloan** [comment]
@marco-leo This isn't the right fix since not all addresses will have a zip.

**Comment by iovaneale** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@alecsloan closing this for now since it shouldn't be merged in as-is.

**Comment by ethanbustad** [comment]
ci:stop

**Comment by alecsloan** [comment]
See #762

**Pull request closed without merging**
