### PR TITLE
 COMMERCE-565 Import user segments and catalog rules with breccia initializer

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
Hey @Commando18, I think we just need to add another source-formatter-suppression like this one: https://github.com/liferay/com-liferay-commerce/blob/7.1.x/source-formatter-suppressions.xml#L30. That should make CI happy.

**Comment by alessiorendina** [comment]
@ethanbustad did it, thanks

**Comment by alessiorendina** [comment]
ci:retest

**Review by ethanbustad — APPROVED** [review]

**Pull request merged**
