### PR TITLE
COMMERCE-704 Schema changes, upgrade processes, service retrofits

### PR DESCRIPTION
**Pull request by ethanbustad**
More on COMMERCE-704 to follow.

This should compile and function just fine, so feel free to merge.

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@marco-leo I think this failure is on us. Will investigate.

**Comment by ethanbustad** [comment]
@marco-leo please review, but don't merge yet - the integration test failures are because we haven't finished all the new functionality yet. I thought we'd be able to push in just this piece of what we're working on, but these failures prove otherwise. We'll just have to merge the whole feature all together.

**Pull request closed without merging**
