### PR TITLE
Commerce 1618 Fix duplication of products and addresses from initializer

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by marco-leo** [comment]
avoid updating of accounts informations

**Comment by alecsloan** [comment]
ci:test

**Pull request merged**
