### PR TITLE
COMMERCE-806-798-799-853-71x-next

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
For 7.1.x: https://github.com/liferay/com-liferay-commerce/pull/477

/cc @igorbeslic @ivicac @matijapetanjek

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:test
/cc @ethanbustad

**Comment by ethanbustad** [comment]
@ZoltanTakacs my bad, I'll consider this passing.

**Comment by ethanbustad** [comment]
Merged.

**Comment by ZoltanTakacs** [comment]
Thank you @ethanbustad ! :) 💙

**Pull request closed without merging**
