### PR TITLE
Commerce 1232 should also fix Commerce 1231

### PR DESCRIPTION
**Pull request by alecsloan**
Let me know if you have any questions.

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
@marco-leo merging this since you workflowed the tickets -- hoping you meant to merge, but just forgot.

**Comment by ethanbustad** [comment]
ci:test

**Pull request merged**
