### PR TITLE
COMMERCE-1302 Only show custom fields section if they exist

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
@marco-leo force push reflects the re-work you requested.

**Comment by ethanbustad** [comment]
Errors should be fixed by https://github.com/liferay/com-liferay-commerce/pull/838 and https://github.com/liferay/com-liferay-commerce/pull/841.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:test
didn't update the private repo with the latest fixes :(

**Comment by ethanbustad** [comment]
ci:test

**Pull request merged**
