### PR TITLE
COMMERCE-2250 Use custom validator for checkout address country field

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
tests should be fixed in upstream now

**Review by ethanbustad — COMMENTED** [review]
Hey @Commando18, couldn't we use an OOTB validator like this:

    <aui:validator name="min">1</aui:validator>

We do that in a few other places -- does that achieve what we need?

**Comment by marco-leo** [comment]
@Commando18 please fix as Ethan indicated, and make sure to review and answer your github notifications

**Comment by alessiorendina** [comment]
@ethanbustad @marco-leo I have updated it, sorry for the delay. Thanks!

**Review by ethanbustad — APPROVED** [review]

**Pull request merged**
