### PR TITLE
COMMERCE API - 2018 FEB 21

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
[Commerce API Scrum board](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=3928)
----
Tickets:
- https://issues.liferay.com/browse/COMMERCE-966
- https://issues.liferay.com/browse/COMMERCE-969
- https://issues.liferay.com/browse/COMMERCE-1038
- https://issues.liferay.com/browse/COMMERCE-1037

/cc @igorbeslic @ivicac @matijapetanjek @Commando18

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by ethanbustad** [comment]
ci:test
Fixed `commerce-theme-breccia` issue in upstream.

**Comment by ZoltanTakacs** [comment]
Thank you @ethanbustad ! 💯👍🙂

**Comment by ZoltanTakacs** [comment]
Resent on https://github.com/liferay/com-liferay-commerce/pull/593

**Pull request closed without merging**
