### PR TITLE
LRQA-43343/43110 | 7.1.x

### PR DESCRIPTION
**Pull request by iovaneale**
https://issues.liferay.com/browse/LRQA-43110
https://issues.liferay.com/browse/LRQA-43343

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:retest

**Comment by iovaneale** [comment]
@marco-leo @Commando18, the failure regards Breccia.

**Comment by ethanbustad** [comment]
@iovaneale I'm working with @petershin to try to get this resolved -- he's been making changes on the portal side to try to prevent this error. Most recent convo here: https://github.com/ethanbustad/com-liferay-commerce/pull/5.

**Comment by iovaneale** [comment]
ci:retest

**Comment by iovaneale** [comment]
ci:retest

**Comment by iovaneale** [comment]
ci:stop

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
Hi @ethanbustad, can you please take a look at this SF error? It's the same error thrown in #94 .

**Comment by ethanbustad** [comment]
@iovaneale, @luca-pellizzon, /cc @marco-leo 

It looks like these are new failures due to [LPS-85296](https://github.com/liferay/liferay-portal/compare/2cc6a37...5e4de2e), but for some reason I can't reproduce the failure locally :(.

I'll try to fix these in upstream today and get these PRs passing.

**Comment by ethanbustad** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:stop

**Comment by iovaneale** [comment]
Sent to #94

**Comment by iovaneale** [comment]
ci:help

**Pull request closed without merging**
