### PR TITLE
COMMERCE-2035 accounts API support Nested Fields

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
…re, and support the nested fields annotation. Addresses, organizations and users are now nested fields.

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
Hi @marco-leo and @ethanbustad just to let you know this PR is for accounts API

**Review by ethanbustad — APPROVED** [review]

**Comment by ethanbustad** [comment]
@andrea-ale-sbarra do these changes require regenerating the REST code (`gw buildREST`)?

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
Hi @ethanbustad , you were right again, also this module needed a buildREST task run. Thank you!

**Pull request merged**
