### PR TITLE
Commerce 1453 Fix 14 SF suppressions. Potential Http classes

### PR DESCRIPTION
**Pull request by alecsloan**
@marco-leo If you don't like any of the class renames I can just drop the specific commit

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:stop

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — COMMENTED** [review]
For the most part I'm ok with these changes... and, btw, thanks for separating out the commits like you did -- very clean.

The new names I don't like are:
* `CPHttpDataSource` -- I feel like this implies that the data is being _sourced_ via http, which may not be the case (and often isn't). Not sure what we would do instead, tho :/
* `CPCompareHttpContentHelper` -- This name just feels a bit clunky.... `CPCompareContentHttpHelper` _might_ be a little better? I guess it depends on how we name other classes related to this functionality. If `CompareContent` is consistently a unit which all together labels this functionality, then we shouldn't split it up in this class name. But if not, then maybe it makes most sense as-is.

**Comment by alecsloan** [comment]
@marco-leo Any feedback? I can't remember if those were the initial ones you asked me to change or if I chose them.

**Comment by marco-leo** [comment]
won't merge sorry, too risky

**Pull request closed without merging**
