### PR TITLE
COMMERCE-686 CSS refactor

### PR DESCRIPTION
**Pull request by gcmznt**

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
Requires https://github.com/liferay/com-liferay-commerce/commit/d16a22357609392e1ec610c79fbcdb7ef95631ab and https://github.com/liferay/com-liferay-commerce/commit/52b11684d66492cf3ae62dfb07902d8bb24582e6.

**Pull request merged**
