### PR TITLE
COMMERCE-1992 Fixed backport of theme deps

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test

**Review by ethanbustad — COMMENTED** [review]
Won't we still need a change like this in both themes? https://github.com/liferay/com-liferay-commerce/pull/1537/files#diff-7f5b463506329143775625a40d19f0caL7

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by gianmarcobrunialti** [comment]
@ethanbustad This change invalidates the PR for the revert (which can be closed now) and fixes the FTL `layout.isSystem` error introduced with the update of the deps in both themes.

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by gianmarcobrunialti** [comment]
@ethanbustad Is there a way to automatically format FTL? In local there's no change at all and needed to format by hand, but I'm missing out on the rules.

**Comment by marco-leo** [comment]
Merged in diff pull

**Comment by ethanbustad** [comment]
@gianmarcobrunialti there _should_ be, but we always end up having these discrepancies between the SF rules that run in CI vs the ones that run locally. When we move away from the subrepo and start developing out of portal this shouldn't happen any more at least :/. In the meantime, I'm not sure there's anything we can do to make it auto-format locally :(

**Pull request closed without merging**
