### PR TITLE
COMMERCE-600 upgrade process for commerce service

### PR DESCRIPTION
**Pull request by luca-pellizzon**
@marco-leo please check the first part of the upgrade process.
There is a TODO for moving the data from 
commercePaymentMethodId column
to
commercePaymentMethodKey

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
@ethanbustad here the upgrade process for COMMERCE-600.

**Comment by marco-leo** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Pull request merged**
