### PR TITLE
COMMERCE-2329 Fix widget errors on empty site in 7.2

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-2329

Hey Marco, let me know what you think of this solution -- especially regarding the channelGroupId issue. This solution may be a little risky, but it took few changes which is nice. We can make the change further down the stack instead, but then it'll just take changing it in more places (I think). Let me know if you want me to change it.

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
baseline passes for me locally... we'll see whether this is a fluke

**Comment by ethanbustad** [comment]
ci:stop
the private branch hadn't been updated yet, so all test fixes may not be included. Will kick off tests again now that private branch is up-to-date

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
fixed SF issue in upstream

**Comment by yichenroy** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
:'(

**Comment by ethanbustad** [comment]
ci:test
looks like tests may be passing elsewhere?

**Comment by ethanbustad** [comment]
ci:test

**Comment by alessiorendina** [comment]
Forwarded to #1729 

You can close this one, thanks!

**Pull request closed without merging**
