### PR TITLE
COMMERCE-1453 fFix JavaModuleServiceProxyFactoryCheck suppression

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by marco-leo** [comment]
@ethanbustad @alecsloan This pull is fine, let's rebase and make tests pass again

**Comment by ethanbustad** [comment]
Rebased and sent along to https://github.com/liferay/com-liferay-commerce/pull/1474.

**Pull request closed without merging**
