### PR TITLE
 COMMERCE-1496 CommerceOrder replace commerceCurrencyId with commerceCurrencyCode

### PR DESCRIPTION
**Pull request by luca-pellizzon**
@marco-leo

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
@luca-pellizzon let's rebase this please, I would like to merge in 2.0.7

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/1512

**Pull request closed without merging**
