### PR TITLE
COMMERCE-1067 - commerce-product-service - Use UUIDs to generate product unique friendly urls

### PR DESCRIPTION
**Pull request by ivicac**
Best Regards

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test

**Comment by ethanbustad** [comment]
@ivicac curious why this issue/fix came up for you. My guess is this isn't the right fix -- we want the URLs to be easy and user-friendly, but `/p/brake-pads-a94a0525-bce5-48e6-902d-faea7a061eb4` isn't particularly friendly 😄

**Comment by ivicac** [comment]
Hi @ethanbustad 
I found this block of code can have an impact on performance when importing a large number of products with the same name.

@marco-leo agreed we should instead use uuids for creating unique friendly urls then.

This PR doesn't need to be merged ASAP. We can discuss it after a vacation when all of us are back.

Best Regards

**Comment by ethanbustad** [comment]
Oh I see..... interesting, ok. Sounds like a good plan :)

**Pull request closed without merging**
