### PR TITLE
COMMERCE-1226 Add handling for null cpInstance

### PR DESCRIPTION
**Pull request by alecsloan**
Let me know if this isn't the correct fix.

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:test

**Pull request merged**
