### PR TITLE
COMMERCE-1120 Rules should only be applied if active

### PR DESCRIPTION
**Pull request by alecsloan**
Let me know if you have any questions.

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by alecsloan** [comment]
force push reflects required rebase

**Review by marco-leo — CHANGES_REQUESTED** [review]
@alecsloan I would prefer avoid loading the cprule that are not activated, adding a condiction   //ccc @ethanbustad

**Comment by alecsloan** [comment]
@marco-leo force push reflect indexer change

**Comment by alecsloan** [comment]
ci:test

**Comment by alecsloan** [comment]
@marco-leo this pull is ready for re-review

**Pull request merged**
