### PR TITLE
COMMERCE-2294

### PR DESCRIPTION
**Pull request by fabio-d-m**
Product detail now compatible with classic themes!

### CODE REVIEW

**Comment by fabio-d-m** [comment]
@marco-leo not tested on speedwell

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
@ethanbustad I think this is failing just because the CI is fetching not the latest version of Commerce, looks like is trying to apply this PR to central 7.1.x branch.

**Comment by fabio-d-m** [comment]
@marco-leo and @ethanbustad please see: https://github.com/liferay/com-liferay-commerce/pull/1725

**Pull request closed without merging**
