### PR TITLE
COMMERCE-1962 | 7.1.x-next

### PR DESCRIPTION
**Pull request by iovaneale**
Adapt tests to Commerce 2.0.x and add new ones for creating Catalogs and Channels

https://issues.liferay.com/browse/COMMERCE-1962

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:retest

**Comment by marco-leo** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:stop

**Comment by yichenroy** [comment]
ci:test
Restarting test to use the newer bundle that became available very recently
https://test-1-0.liferay.com/userContent/bundles/test-portal-acceptance-upstream(7.1.x)/1120/

**Comment by iovaneale** [comment]
@yichenroy So should I remove the test.run.environment= "EE" property?

**Comment by yichenroy** [comment]
@iovaneale 
yes if those tests are meant to be run in the public environment

**Comment by marco-leo** [comment]
@yichenroy how we do run test using the last DXP?

**Comment by yichenroy** [comment]
@marco-leo 
You'll need to send a pull request from `com-liferay-commerce-private` with a `-private` branch, the latest 7.1.x-private upstream sha is `66eee2777c0906979157a8d10f207b6b2ca0c440` here:
https://test-1-0.liferay.com/userContent/bundles/test-portal-acceptance-upstream(7.1.x-private)/842/

**Comment by marco-leo** [comment]
@yichenroy
that means that every pull request we do merge in the public branch is actually not triggering test in the DXP and that we do have to make a new pr in a diff repo for every pull in the public?

**Comment by yichenroy** [comment]
@marco-leo 
Yes, if you want to trigger all tests (particularly the `private-only`) it will need to be done on a `-private` branch, i.e `7.1.x-private`, the public branches will only run public tests. DXP includes all the private modules, and DXP testing includes the private tests on top of CE (public) tests.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
The poshi failure is actually accurate. Merging

**Pull request merged**
