### PR TITLE
COMMERCE-525 Fixed breccia ADTs

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
@Commando18 I think you just need to switch `commerce-cart-content-web/build.gradle` to importing the `commerce-cart-taglib` project rather than the version 1.0.0 jar -- I think that's why the JSP is failing to compile.

**Comment by alessiorendina** [comment]
@ethanbustad I did it now, thanks! 👍

**Comment by alessiorendina** [comment]
ci:retest

**Comment by marco-leo** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:retest

**Comment by ethanbustad** [comment]
`commerce-cart-taglib` didn't have compile-time access to the changes you're making to `commerce-taglib`, so `compileJSP` fails. Changed to a project dependency to fix, and sent to https://github.com/liferay/com-liferay-commerce/pull/120.

**Pull request closed without merging**
