### PR TITLE
Commerce 2035 parent class

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
Hi @marco-leo, this should fix the bug on the nestedFields of the orders. Let me know if it is ok to use this PR or I need to open a new issue on JIRA for this, I'm not 100% sure for the comments in the commit messages..

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Review by ethanbustad — COMMENTED** [review]
Hey @andrea-ale-sbarra, does this require a `gw buildREST`? If not, everything looks good to me :)

**Comment by andrea-ale-sbarra** [comment]
Hi @ethanbustad , I've just run the buildREST task on all the modules involved in this PR, but nothing changed, so I think the work is complete as of now.

**Review by ethanbustad — APPROVED** [review]

**Comment by ethanbustad** [comment]
ci:test
tests should be fixed in upstream now

**Pull request merged**
