### PR TITLE
COMMERCE-928 - commerce-openapi-core-impl - Register message providers only to those applications ending with  “.Rest”

### PR DESCRIPTION
**Pull request by ivicac**
Best Regards

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by ethanbustad** [comment]
@jpince @pyoo47 @yichenroy could you guys help us figure out the cause of this issue as soon as possible? Doesn't make any sense to me, but it looks like a CI or portal issue -- could it be related to the M2 release that went out on Friday? We're hoping to release a new version of Commerce Mon Feb 4, which is probably "today" by the time you read this, and we're flying blind atm :/

**Comment by pyoo47** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
Closing this one, I'll introduce new service properties for the extensions we provide, so the App can decide if it wants to use it or not.

**Comment by ZoltanTakacs** [comment]
-> https://github.com/liferay/com-liferay-commerce/pull/522

**Comment by pyoo47** [comment]
@ethanbustad The issue you encountered was caused by an squid outage that has now been resolved.

https://loop.liferay.com/home/-/loop/feed/15947857

**Comment by ethanbustad** [comment]
Thanks, @pyoo47 !!

**Pull request closed without merging**
