### PR TITLE
Use most recent Service Builder

### PR DESCRIPTION
**Pull request by ethanbustad**
Supercedes https://github.com/liferay/com-liferay-commerce/pull/67.

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:retest

**Comment by ethanbustad** [comment]
ci:retest

**Comment by ethanbustad** [comment]
ci:retest

**Comment by ethanbustad** [comment]
Looks like these failures are caused by the Poshi update: https://loop.liferay.com/web/guest/home/-/loop/feed/13007345.

**Comment by ethanbustad** [comment]
ci:retest

**Comment by jpince** [comment]
@kenjiheigel can you please audit the commerce sub repos for any further POSHI changes needed? Thanks! You can send any changes to @ethanbustad since Alessandro's on PTO.

https://github.com/liferay/com-liferay-commerce
https://github.com/liferay/com-liferay-commerce-private

**Comment by ethanbustad** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@jpince, just checked on commerce and commerce private. Looks like @ethanbustad got all the changes in https://github.com/liferay/com-liferay-commerce/pull/68/commits/903a6d2207269738f7d46c361a3252ab2b6f6f3a. Sorry about that! I forgot commerce has a different workflow. Let me know if there's any other issues!

**Comment by ethanbustad** [comment]
@jpince, @kenjiheigel -- thanks, guys!

**Comment by jpince** [comment]
@michaelhashimoto @kenjiheigel @yichenroy can you please look into this?
```
java.lang.IllegalArgumentException: Unknown test class group
```

**Comment by yichenroy** [comment]
@jpince @ethanbustad 
Regarding unknown test class group error: this is an issue in the build scripts, we will work on resolving it as soon as possible. 

Please follow this ticket for details and progress:
https://issues.liferay.com/browse/LRQA-42798

**Comment by ethanbustad** [comment]
@yichenroy thanks!

**Pull request merged**
