### PR TITLE
Pr 1521

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by ethanbustad** [comment]
ci:test
maybe it'll work this time? (the error doesn't really make sense, and we can't reproduce it locally)

**Comment by alessiorendina** [comment]
ci:test

**Comment by fabio-d-m** [comment]
@wincent here's the new PR

**Comment by ethanbustad** [comment]
Looks like an updated version of this was sent to https://github.com/liferay/com-liferay-commerce/pull/1536?

**Comment by fabio-d-m** [comment]
@ethanbustad sorry I missed to notify that this pr can be closed :/

This one replaces it: https://github.com/liferay/com-liferay-commerce/pull/1536

**Pull request closed without merging**
