### PR TITLE
COMMERCE-2377 Fix CSS behavior around control menu

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-2377

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by yichenroy** [comment]
@ethanbustad 
Looks like it didn't work, I'll open a pull request to myself to continue testing.

**Comment by ethanbustad** [comment]
ci:test
Roy's fix was just merged to upstream -- we'll see if it's applied yet

**Comment by ethanbustad** [comment]
@iovaneale looks like a bunch of language properties aren't getting translated properly, so the test doesn't find the expected text. Not sure why localization is failing.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by brianwulbern** [comment]
@yichenroy is this related to the changes we need in: https://issues.liferay.com/browse/LRCI-795?

**Comment by yichenroy** [comment]
@brianwulbern yes, the integration failure is related to the changes we need in https://issues.liferay.com/browse/LRCI-795, however the functional failure is unrelated.

**Comment by ethanbustad** [comment]
Yeah, working on a fix for the functional failure. Hopefully we'll merge it in today 🤞

**Comment by yichenroy** [comment]
We'll prioritize the parts that affect subrepository tester under this ticket: 
https://issues.liferay.com/browse/LRCI-844

cc @ethanbustad @brianwulbern @petershin

**Comment by marco-leo** [comment]
see : https://github.com/liferay/com-liferay-commerce/pull/1742

**Pull request closed without merging**
