### PR TITLE
COMMERCE-778 Misc fixes

### PR DESCRIPTION
**Pull request by ethanbustad**
Based off of https://github.com/liferay/com-liferay-commerce/pull/384.

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
Hey @yichenroy @pyoo47, `com.liferay.commerce.organization.web` is a module that we've removed from our subrepo since the hash that's been merged to central. So... it seems like what's happening is our repo is being copied into the `modules/apps/commerce` directory in portal, but it's not being cleared first. But it seems like this will always cause problems when we delete files and the deletes haven't yet been merged into central. Does this make sense to you guys? Is there any way we can fix this?

**Comment by yichenroy** [comment]
@ethanbustad 
We are deleting all files in `modules/apps/commerce` before we copy in files from the Commerce repository except for these files/directories `.gradle, .gitrepo, gradle, and ci-merge`.

I believe the problem here is that we are using a pre-built bundle to save time, but in this case we should build the bundle from scratch. We may have to find a way to detect whether we should build the bundle or not based on the commits.

**Comment by ethanbustad** [comment]
@yichenroy got it, thanks.

**Comment by yichenroy** [comment]
@ethanbustad 
Here's the ticket for this issue: https://issues.liferay.com/browse/LRQA-46019

**Pull request merged**
