### PR TITLE
Commerce 2291 Hide Account Selector and Mini Cart on checkout page

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
^ a fix for this has been committed to master at least. May need to be backported.

**Comment by alecsloan** [comment]
One last go
ci:test

**Comment by alecsloan** [comment]
ci:test

**Pull request merged**
