### PR TITLE
COMMERCE-566 Added default measurement units to breccia initializer

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:retest

**Comment by ethanbustad** [comment]
Looks like this failure is in the base bundle -- https://testray.liferay.com/home/-/testray/case_results/419992135. We can probably go ahead and ignore it.

**Comment by ethanbustad** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/99

**Pull request closed without merging**
