### PR TITLE
COMMERCE-686 Fixed account management

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
@Commando18 these failures aren't your problem -- they're present in portal upstream.

Hopefully they're fixed there soon :)

**Comment by ethanbustad** [comment]
Should be fixed by https://github.com/brianchandotcom/liferay-portal/pull/67444.

**Comment by marco-leo** [comment]
sent to https://github.com/liferay/com-liferay-commerce/pull/510

**Pull request closed without merging**
