### PR TITLE
Fix frontend build issue

### PR DESCRIPTION
**Pull request by ethanbustad**

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
this is ridiculous

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
Just in case the outstanding build issue was caused by the dns problems we had today. @marco-leo if this passes, feel free to merge and test the other pulls. (But I don't really expect it to pass 😢.)

**Comment by marco-leo** [comment]
ci:test

**Pull request merged**
