### PR TITLE
COMMERCE-APIs - Feb 06

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
[Commerce API Scrum board](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=3928)
----
Tickets:
- https://issues.liferay.com/browse/COMMERCE-911
- https://issues.liferay.com/browse/COMMERCE-952
- https://issues.liferay.com/browse/COMMERCE-878

/cc @matijapetanjek @igorbeslic

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
@matijapetanjek please note that the getters for boolean type on Models should be invoked by **is**XYZ otherwise we get these CI errors: https://github.com/liferay/com-liferay-commerce/pull/533#issuecomment-461049490

Thanks!

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
Forwarded to https://github.com/liferay/com-liferay-commerce/pull/542

**Pull request closed without merging**
