### PR TITLE
LRQA-47897 | 7.1.x-next

### PR DESCRIPTION
**Pull request by iovaneale**
https://issues.liferay.com/browse/LRQA-47897

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
@ZoltanTakacs can you look into this SF failure?

**Comment by ZoltanTakacs** [comment]
@iovaneale please see the fix for it https://github.com/liferay/com-liferay-commerce/pull/749
/cc @marco-leo

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
@ZoltanTakacs unfortunately, the pull keeps failing, but because of a different error. The same failure on #748

**Comment by ethanbustad** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
@marco-leo All test passed, you can merge. :)

**Pull request merged**
