### PR TITLE
COMMERCE-745 set translation based on locale

### PR DESCRIPTION
**Pull request by ethanbustad**
https://issues.liferay.com/browse/COMMERCE-745

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
Hey @jpince, these integration test failures started a week or so ago, and apparently they stem from a change in portal (Roy told me at https://github.com/liferay/com-liferay-commerce/pull/336#issuecomment-450258482, and I've been hoping it'd go away, but it hasn't so far). Do you know whether this is a regression that needs to be fixed in portal, or a necessary change that we need to adjust to on our end?

**Comment by jpince** [comment]
@ethanbustad it's on Commerce Team right now. You either need to fix it on your end or convince a portal product team that there's an issue in their component that needs to be fixed.

**Comment by ethanbustad** [comment]
Alright, thanks @jpince. I'll talk to someone on our team who knows what these tests are doing :sweat_smile:.

**Pull request merged**
