### PR TITLE
COMMERCE-740 Fixed virtual product's terms of use

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:d26aacd923882d29c47d696a57bf165ff36aa352

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
Updated 7.1.x-next branch in private repo.

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
Updated private repo.

**Comment by ethanbustad** [comment]
@Commando18 from the test failure above, it looks like this change breaks `CommerceVirtualOrderItemLocalServiceTest.testAddCommerceVirtualOrderItem`.

EDIT: Never mind.... that test also fails here: https://github.com/liferay/com-liferay-commerce/pull/293#issuecomment-446012700. Going to look into where this failure is coming from.

**Comment by ethanbustad** [comment]
ci:test
I think the failure must just be a flaky test -- it passes on other PRs built off the same upstream hash, but I can't think of any way this PR would've actually broken the test. We'll see if it fails a second time.

**Comment by ethanbustad** [comment]
ci:test
ugh, updated private again

**Comment by alessiorendina** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Pull request merged**
