### PR TITLE
COMMERCE-1453 bnd suppression fixes (from Alec)

### PR DESCRIPTION
**Pull request by ethanbustad**
Fixes for:

commerce-media-impl/bnd.bnd
commerce-price-list-web/bnd.bnd
commerce-product-type-simple/bnd.bnd
commerce-service/bnd.bnd
commerce-shipping-web/bnd.bnd

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
I _think_ the failure was a fluke in the test env. I don't get the error locally, so retesting.

**Comment by ethanbustad** [comment]
ci:test
hmmmm... we'll try one more time

**Comment by ethanbustad** [comment]
ci:test
maybe it's happy now?

**Comment by pyoo47** [comment]
I'm going to run another test to try to freeze the build when the failure occurs so we can investigate what's going on. Please disregard any additional test results.

**Comment by ethanbustad** [comment]
Alec reclaimed this, so closing :).

**Pull request closed without merging**
