### PR TITLE
COMMERCE-1244 Fix getUniqueUrlTitles

### PR DESCRIPTION
**Pull request by alecsloan**
Let me know if you have any questions.

Almost seems like this method should be named "getNotNullUrlTitles" @marco-leo

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:test

**Pull request merged**
