### PR TITLE
COMMERCE-1647 replace jackson-databind dependency due to vulnerabilities

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test

**Comment by luca-pellizzon** [comment]
ci:test

**Comment by ethanbustad** [comment]
I think I just merged this change separately, haha...

**Comment by luca-pellizzon** [comment]
@ethanbustad do we still need this PR if you merged the same changes in a separate one?

**Comment by ethanbustad** [comment]
It's probably worth checking that the whole diff is taken care of -- if so, then we should be able to just close this PR.

**Comment by luca-pellizzon** [comment]
Changes already merged in a different PR.
Diff checked, no need for this PR anymore

**Pull request closed without merging**
