### PR TITLE
COMMERCE-1495 Move shipping as billing checkbox so it's not disabled …

### PR DESCRIPTION
**Pull request by alecsloan**
…on address change

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by marco-leo** [comment]
merged

**Comment by ethanbustad** [comment]
@marco-leo where is this merged to? I don't see it in upstream anywhere.

**Comment by alecsloan** [comment]
ci:test

**Comment by marco-leo** [comment]
rebased: https://github.com/liferay/com-liferay-commerce/pull/1118 . Thanks

**Pull request closed without merging**
