### PR TITLE
Commerce 2525 2

### PR DESCRIPTION
**Pull request by riccardo-ferrari**

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test

**Comment by riccardo-ferrari** [comment]
@ethanbustad , this should cover all your previous requests. Thanks
@marco-leo changes as requested

**Comment by riccardo-ferrari** [comment]
ci:stop

**Comment by riccardo-ferrari** [comment]
ci:test

**Review by ethanbustad — APPROVED** [review]

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test
that error should be fixed in upstream now....

**Pull request merged**
