### PR TITLE
COMMERCE-704 | COMMERCE-1234 | COMMERCE-1236 | COMMERCE-1408

### PR DESCRIPTION
**Pull request by alessiorendina**
- Catalog APIs
- Account APIs

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:stop

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
@iovaneale can you please take a look at it?

**Comment by iovaneale** [comment]
@Commando18 The test fails to click the "View On Store Front" link. Actually, from the screenshots, it came out the button is missing, that's why I would suggest retesting. It looks like an unreliable failure.

**Comment by iovaneale** [comment]
ci:retest

**Pull request merged**
