### PR TITLE
COMMERCE-1981 Account management table content is wider

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by gianmarcobrunialti** [comment]
ci:test

**Review by ethanbustad — CHANGES_REQUESTED** [review]
I'll take a look at the `generateJSPJava` failure, but in the meantime, this'll most likely fail SF because of whitespace issues. Can you run it and check? The file shouldn't end in a newline (which SF should do automatically), and the indentation in the body of the `liferay-frontend:screen-navigation` tag looks like it's too deep (which SF may or may not correct, but we should make sure it gets fixed).

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
@gianmarcobrunialti when you push changes, please notify with a comment in the PR

**Review by ethanbustad — APPROVED** [review]

**Comment by marco-leo** [comment]
@ethanbustad can you help with this pull?

**Comment by ethanbustad** [comment]
Just need to update a dependency:

    compileOnly group: "com.liferay", name: "com.liferay.frontend.taglib", version: "3.0.0"

to version `3.2.0` (I think) -- in `commerce-account-web`

**Comment by gianmarcobrunialti** [comment]
ci:test

**Comment by ethanbustad** [comment]
The SF output isn't the easiest thing to read.... but auto SF should fix this; or, just sort the attributes and remove the trailing newline (I _think_ that's all it's complaining about).

**Comment by ethanbustad** [comment]
ci:test

**Pull request merged**
