### PR TITLE
COMMERCE-1222 Commerce Account admin portlet

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by ethanbustad** [comment]
Hey @Commando18, it looks like you're changing some existing service methods (it's a big diff, so it's hard for me to tell). Could you leave the existing ones there, and only add new ones? Changes like this might be hard for customers to adjust to, but if we can keep the existing signatures present (even deprecating them if we want), I think that should help the upgrade transition a lot.

**Comment by marco-leo** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Comment by ethanbustad** [comment]
ci:test

**Comment by alessiorendina** [comment]
ci:test

**Pull request merged**
